### ISSUE TITLE
Superior Collection Vol 2 disc image doesn't run

### ISSUE THREAD

**Issue by richtw1** [mattgodbolt/jsbeeb#100]
http://bbc.godbolt.org/?disc=sth%3ASuperior%2FSuperiorCollectionVol2.zip#

*/INIT is intercepting some file system vectors and making loading 40/80 track agnostic.  Surprisingly B-Em runs this OK, but jsbeeb is getting stuck (hangs in the DFS waiting for FE80 bit 7 to clear).  This I assume will work OK once 'proper' disc emulation with a raw bit-level disc image is done.

By the way, INIT is the work of a certain Kevin Edwards :)

**Comment by scarybeasts** [comment]
@richtw1 @mattgodbolt Seems to work fine for me -- both before and after my recent i8271 fixes. Maybe something else fixed this long ago? Can close?

**Comment by mattgodbolt** [comment]
Yeah, this seems fixed by ...something... along the way. Thanks for rechecking! Closing: @richtw1 can reopen if he finds something still amiss.
