### ISSUE TITLE
Pro-Boxing Simulator hangs after loading

### ISSUE THREAD

**Issue by richtw1** [mattgodbolt/jsbeeb#104]
http://bbc.godbolt.org/beta/?tape=sth%3ACodemasters%2FProBoxingSimulator_B.hq.zip#

Gets stuck in a loop at &6034, waiting for bit 1 of &FE08 to be set.  This is some pretty weird code actually:

```
6024  LDA #$fd
6026  STA $21
6028  LDA #$67
602a  STA $20
602c  LDY #$a9
602e  LDA #$09
6030  STA ($20),Y ; &fe10
6032  LDY #$a1
6034  LDA ($20),Y ; $fe08
6036  AND #$02
6038  BEQ $6034
603a  STA $00
603c  STA $01
603e  INY
603f  STA ($20),Y ; $fe09
6041  DEY
6042  LDA ($20),Y ; $fe08
6044  AND #$02
6046  BNE $6050
6048  INC $00
604a  BNE $6042
604c  INC $01
604e  BNE $6042
```

Given the obfuscation of &FE08 etc, my guess is this is designed to break when transferred to disc.  AUG says that is &FE08 bit 1 is Transmit Data Register Empty.  It waits for it to be empty, then writes a byte to the transmit data register, and checks immediately that it's full.  If it doesn't show as full within X iterations, it takes a different path.  Not really sure what's going on there, or indeed if it would really break even if the disc system was running.

But I presume the solution is just to emulate the very basics of tape writing, i.e. set FE08 bit 1 most of the time, clear it when write to FE09, set it again after a small amount of time.

**Comment by mattgodbolt** [comment]
Nice spot! Yeah sounds very plausible: I think you have a better
understanding on this one than me. Will do some reading of the AUG...

**Comment by scarybeasts** [comment]
c8e9d5384087c4e201ef101d9eb3be9e755c0db8afb4ece6d668ef4b647961ae  ProBoxingSimulator_B.hq.zip

Loads fine. I even headbutted my way to victory in round 1 of the junior championship.

Appears something fixed this over the last 4 years.... closing.

**Comment by scarybeasts** [comment]
@richtw1 I just hit this in beebjit.

I think I know why it might work as a simple copy protection. If the code was loaded from disc, the default MOS state of "R423 selected" will apply and assuming there's nothing connected to the port, the serial byte write won't be consumed. If the code was loaded from tape, the state "tape selected" will apply and the serial byte write is always consumed (it's how the serial ULA works).

**Comment by mattgodbolt** [comment]
OH hahaha! How funny :-)
