### ISSUE TITLE
Clogger hangs if run from cold boot

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#105]
From a beeb image: http://bbc.godbolt.org/?disc=sth%3AImpact%2FClogger.zip# hangs (hitting a HLT at 0x2a2e seemingly executing some ASCII...)

Works fine on Master, and works from a warm boot.

**Comment by scarybeasts** [comment]
This one is interesting. The sequence is this:

- jsbeeb initializes memory to 0xFF upon hard reset.
- MOS 1.2 boots, and does not appear to use 0x9E for anything.
- P.?&9E gives 255 (other emulators, presumably a real beeb, give 0).
- Clogger starts to fail here, eventually trashing IRQV &0204, causing a wild jump:
[ITRP] 1279: LDA $9E
[ITRP] 127B: BEQ $1282
[ITRP] 127D: INC $9E
[ITRP] 127F: JMP $1D87
[ITRP] 1282: CLI
[ITRP] 1283: RTS

Clogger essentially reads &9E without ever writing it, so it relies on zero initialization.

**Comment by scarybeasts** [comment]
http://bbcmicro.co.uk/game.php?id=743 notes "Beebem problems with DFS 1.20" and launches a master model to compensate.

However, I think the reason the master model works is not DFS related, but because the TERMINAL ROM appears to initialize the zero page to 0x00:

    8000 : 4C 77 AF 4C 72 9D C2 11 01 54 45 52 4D 49 4E 41   Lw�Lr��..TERMINA
    8010 : 4C 00 28 43 29 31 39 38 34 20 41 63 6F 72 6E 00   L.(C)1984 Acorn.

    8056 : STZ 01      
    8058 : STZ 00      
    805A : STA (00),Y  
    805C : INY         
    805D : BNE 805A

**Comment by scarybeasts** [comment]
There's a complication with fixing this.

Whereas Clogger seems to rely on &9E being zero initialized, there's another long and interesting thread where Eagle Empire appears to rely on &800 being 0xFF initialized:
https://stardot.org.uk/forums/viewtopic.php?f=7&t=4927
The same thread then goes into analysis of many BBC machines, some of which power on with 0xFF in most memory locations and others which power on with 0x00 in most memory locations. Eagle Empire is found to work on some real beebs but not others.
