### ISSUE TITLE
Sound runs slowly on MS Edge browser

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#106]
c.f. Kieran Connell's issues (he has shared over email a private example that is super slow on MS Edge). Same example runs fine on Firefox and Chrome.

**Comment by murkle** [comment]
From a quick test, sound in Labyrinth seems OK

Speech at start of Repton 2: there's extra buzzing for the first word "superior" then it seems OK. Sound in the game seems OK

Testing on Windows 10 Insider Build 11102

**Comment by scarybeasts** [comment]
@mattgodbolt Given that Microsoft Edge is switching to the Chromium engine, should we simply close this?

**Comment by mattgodbolt** [comment]
I guess we could... if anyone still cares about "legacy" Windows browser support, speak up and I'll reopen :D (@kieranhj ?)

**Comment by kieranhj** [comment]
What’s Edge? ;)
