### ISSUE TITLE
Feature: Allow background image around JSbeeb window

### ISSUE THREAD

**Issue by sassquad** [mattgodbolt/jsbeeb#108]
Sometime before Christmas, I hosted the zipped SSD for the game Runemaker Codename Druid, a mammoth type in game from Acorn User magazine, published in April 1989.

At the time, the magazine did some lovely illustrations to accompany articles. The ones made for the article accompanying the game listing were especially good, indeed it was the main cover illustration.

Would it be possible to allow for a background tile to be positioned around the JSBeeb monitor, when referencing said game? The image could be hosted at the same location as the zip/ssd, and referenced in the URL. The Druid illustrations are an ideal example of what it could look like.

If necessary, I'll perform a mockup screenshot showing what I'd like to see.

One useful aspect to this feature is that simple keyboard instructions can be shown on the bg image - not all games present keyboard instructions. For new players, having onscreen instructions within the image would be even better.

**Comment by mattgodbolt** [comment]
Great idea: one also that's been suggested for Elite and Exile too. I very
fondly remember Codename: Druid!

If you want to play with the HTML and suggest an appropriate edit I'm happy
to accept patches. Or if you have a bitmap I can play with I can try some
ideas.

**Comment by mattgodbolt** [comment]
A mockup would also work perfectly too!

**Comment by sassquad** [comment]
Here's a mockup image of what I'm looking for:

![runemaker mockup](https://cloud.githubusercontent.com/assets/2427885/13138312/51a3ddce-d61e-11e5-9e97-66316e6e8554.jpg)

You could tile the background image with some CSS for the body tag, and another background image for any other tag, as long as they are set as center left top / center right top, they will always be nearest to the monitor, to cater to smaller screen resolutions.

**Comment by mattgodbolt** [comment]
Thanks!

**Comment by BigEd** [comment]
can you use z-index in the CSS to put the image behind the screen element, and therefore not need a blank section in the middle?

**Comment by sassquad** [comment]
I went for simplicity here, a single background image centered top would be the easiest approach, even if you get a wasteful void in the middle.

Jpeg is an obvious choice, you may get reasonable filesize/quality balancing. Depends on the image in question. Simplistic instructions may only warrant a small graphic PNG file to the left or right of the canvas.

Perhaps we need some attributes concerning bg image positioning?

**Comment by mattgodbolt** [comment]
Hi all!

I went for a new approach: add support for left, right and bottom images. The beta site has them now....e.g.

http://bbc.godbolt.org/beta/?sbLeft=images/sidebar.png&sbRight=images/sidebar.png&sbBottom=images/botbar.png

The new URL params (documented in the README):

sbLeft / sbRight / sbBottom - a URL to place left of, right of, or below the cub monitor. The left and right should be 200x648 and the bottom image should be 896x100.

I can of course adjust the sizes a bit, but these are the sizes that fit onto my (fairly typical I think) full-size laptop screen :)

Comments welcomed! Also we should think about having a list of known disc images and auto-apply sets of sidebars if detected!

**Comment by mattgodbolt** [comment]
Actually I tried hacking the picture you gave together and realised the size constraints would be a problem. So no longer is that required...

I took the liberty of hacking the icture and checking it in:

http://bbc.godbolt.org/beta/?sbLeft=images/sb/CD-left.jpg&sbRight=images/sb/CD-right.jpg - how does that look to you?

(hope you don't mind me using the images you made)

**Comment by sassquad** [comment]
@mattgodbolt Sorry for the delay, that looks great. No worries about use of imagery - I just grabbed the scan of it from 8bs.com, and performed some slicing with an online editor.

Thanks for doing this, much appreciated!

**Comment by mattgodbolt** [comment]
No worries! Hope it works out ok :)
