### ISSUE TITLE
Work around Chrome bug (was Google Drive write access is broken)

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#113]
Seems the scope I've picked allows only read-only access: https://developers.google.com/drive/v2/web/scopes#google_drive_scopes 

It's not clear what the "right" setting is: the old setting (of just drive) allows read/write to all files. I just want read/write to files _I_ create...

**Comment by mattgodbolt** [comment]
Scratch that; I think we're OK...the issue is really:
google-drive.js:78Uncaught illegal access

**Comment by mattgodbolt** [comment]
The culprit is code that does:

`btoa(String.fromCharCode.apply(null, new Uint8Array(100*1024)));`

which works fine in FF

**Comment by mattgodbolt** [comment]
I'll implement https://gist.github.com/jonleighton/958841 or similar. Have reported bug to Google.

**Comment by scarybeasts** [comment]
Works fine in the latest Chrome.

**Comment by scarybeasts** [comment]
Actually still problems... re-opening.

**Comment by mattgodbolt** [comment]
Thanks: I'm updating the site now
