### ISSUE TITLE
Website down...

### ISSUE THREAD

**Issue by BigEd** [mattgodbolt/jsbeeb#118]
http://bbc.godbolt.org/
is not responding!

**Comment by mattgodbolt** [comment]
Yeah - sadly AWS (which hosts everything I do) is having a bit of a nightmare at the moment (http://status.aws.amazon.com/ see the ECC for N Virginia...)

It means I can't restart the instance that is hosting everything...I'm trying my best right now!

**Comment by BigEd** [comment]
Wow - that's a bit bigger than one website being down...

**Comment by mattgodbolt** [comment]
Should be back now! :) All the changes I mentioned elsewhere are only on the beta site fwiw https://bbc.godbolt.org/beta

**Comment by BigEd** [comment]
Right - thanks! (This minor crisis has prompted to me to run from a local Git workspace, so long as I remember to do that.)
