### ISSUE TITLE
JSBeeb fails in Safari

### ISSUE THREAD

**Issue by ahope1** [mattgodbolt/jsbeeb#120]
The version of JSBeeb currently live at http://bbc.godbolt.org doesn't work in either the Safari desktop browser or the Safari iOS browser. It _used_ to work in both (disregarding the lack of keyboard in iOS, obviously).

However, the version of JSBeeb at http://bbcmicro.co.uk/jsbeeb/ _does_ work in Safari, both desktop and iOS.

**Comment by mattgodbolt** [comment]
Can you elaborate on what doesn't work? I don't have access to Safari I'm afraid! Are there any errors in the JavaScript console? Thanks in advance!

**Comment by ahope1** [comment]
I will do shortly, but basically nothing happens at all! The image of the CUB monitor loads up, etc., but the "screen" inside the monitor remains completely black.

**Comment by mattgodbolt** [comment]
Thanks!!

**Comment by ahope1** [comment]
Here's the console log. I don't really understand it (and in particular I'm not sure why the Ghostery (adblocker) entries are in there as I'd temporarily disabled Ghostery!) but hopefully it'll make more sense to you!:

[Warning] Unexpected CSS token: : (bootstrap.min.css, line 1)
[Warning] Unexpected CSS token: : (bootstrap.min.css, line 1)
[Warning] Unexpected CSS token: : (bootstrap.min.css, line 1)
[Log] GL Canvas set up (main-9aebbc717619aa1d1181f5bda9f3691c33a0d4b4.js, line 8)
[Error] ReferenceError: Can't find variable: typeOf
	(anonymous function) (main-9aebbc717619aa1d1181f5bda9f3691c33a0d4b4.js:10:1483)
	execCb (require.js:1:11472)
	check (require.js:1:6033)
	enable (require.js:1:8417)
	init (require.js:1:5161)
	(anonymous function) (require.js:1:10021)
[Error] Blocked a frame with origin "https://accounts.google.com" from accessing a frame with origin "http://bbc.godbolt.org".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.

	global code (ghostery-min.js (line 8:10044))
[Error] Blocked a frame with origin "https://apis.google.com" from accessing a frame with origin "http://bbc.godbolt.org".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.

	global code (ghostery-min.js (line 8:10044))
[Error] Blocked a frame with origin "http://platform.twitter.com" from accessing a frame with origin "http://bbc.godbolt.org". Protocols, domains, and ports must match.
	global code (ghostery-min.js (line 8:10044))

**Comment by ahope1** [comment]
Just to add that JSBeeb runs properly in the Chrome desktop browser on my Mac. (On the same Mac (running OS X 10.10.5 Yosemite), JSBeeb fails to run in Safari v9.1.2 (10601.7.7)).

**Comment by mattgodbolt** [comment]
Can you try hitting https://bbc.godbolt.org (that is, the https site?) Thanks!

**Comment by ahope1** [comment]
Tried it using desktop Safari. No joy.  :-(

[Warning] Unexpected CSS token: : (bootstrap.min.css, line 1)
[Warning] Unexpected CSS token: : (bootstrap.min.css, line 1)
[Warning] Unexpected CSS token: : (bootstrap.min.css, line 1)
[Error] Blocked a frame with origin "https://accounts.google.com" from accessing a frame with origin "https://bbc.godbolt.org". Protocols, domains, and ports must match.
	global code (ghostery-min.js (line 8:10044))
[Error] Blocked a frame with origin "https://apis.google.com" from accessing a frame with origin "https://bbc.godbolt.org". Protocols, domains, and ports must match.
	global code (ghostery-min.js (line 8:10044))
[Log] GL Canvas set up (main-9aebbc717619aa1d1181f5bda9f3691c33a0d4b4.js, line 8)
[Error] ReferenceError: Can't find variable: typeOf
	(anonymous function) (main-9aebbc717619aa1d1181f5bda9f3691c33a0d4b4.js:10:1483)
	execCb (require.js:1:11472)
	check (require.js:1:6033)
	enable (require.js:1:8417)
	init (require.js:1:5161)
	(anonymous function) (require.js:1:10021)
[Error] Blocked a frame with origin "https://platform.twitter.com" from accessing a frame with origin "https://bbc.godbolt.org". Protocols, domains, and ports must match.
	global code (ghostery-min.js (line 8:10044))

**Comment by mattgodbolt** [comment]
Actually, scratch that (unless you have a spare moment!) The real error is the "typeOf" thing referred somewhere in require.js (!). Utterly mysterious: I'll have to see if I can debug on a real Safari setup with a non-compressed source.  If you have the time and wherewithal to run your own local server, grabbing the source and pointing Safari at a local checkout would be extremely useful! Thanks again!

**Comment by ahope1** [comment]
I may be some time...

**Comment by mattgodbolt** [comment]
Thanks: any help is appreciated. I'm hoping it's a one-line fix for something I can easily diagnose!

**Comment by ahope1** [comment]
It's not that you've accidentally capitalized the "O" in "typeOf", is it?!

**Comment by mattgodbolt** [comment]
Could be...! Good idea; away from a computer for the next hour or two but will give it a try! Thanks!

**Comment by mattgodbolt** [comment]
That was exactly it!

Can you give https://bbc.godbolt.org/beta a spin and let me know if it's fixed? Thanks so much!

**Comment by ahope1** [comment]
Now I get a different error!

TypeError: Not enough arguments
decodeAudioData
(anonymous function) — main-e67c3667552aec00b90dd2aa3a5dce3d4bb26764.js:5:31085
promiseReactionJob

![1](https://cloud.githubusercontent.com/assets/11441088/17573159/9049c42e-5f50-11e6-891e-a07f490a9e20.jpg)

**Comment by mattgodbolt** [comment]
Thanks: seems the audio API changes I made for disc drive noises aren't working. So glad you found this! Will dig further

**Comment by ahope1** [comment]
Line 5189 is:

`return n.decodeAudioData(t.buffer)`

**Comment by ahope1** [comment]
Again, the beta site does work in chrome, just not in Safari.

**Comment by mattgodbolt** [comment]
Ok: seems that Safari only supports the old style of that function. https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/decodeAudioData - I'll fix...

**Comment by mattgodbolt** [comment]
I just pushed a change to the beta site which ought to fix it. When you have a spare moment (and are awake!) I'd appreciate another test!

**Comment by ahope1** [comment]
Now the emulator seems to work -- but there's no sound! (Except for the disc drive noises, which do play.) The emulated Beeb itself isn't outputting sound (e.g. VDU 7, etc.).

**Comment by mattgodbolt** [comment]
Oh! Nothing's ever simple is it hahah! Thanks so much for the help so far.
I will dig through and see if I can see what's going on.

**Comment by mattgodbolt** [comment]
I've just stared at the differences in the code between the disc-drive noise and the version on bbcmicro and I'm blowed if I can see any pertinent differences. I'm going to ask around at work tomorrow to see if anyone has a spare OSX laptop I can play with to see if I can work uot what's going on!

**Comment by ahope1** [comment]
Hope you figure it out. It's the same no-sound problem in Mobile Safari on iOS, btw. But perhaps jsBeeb never did have sound on iOS? The version on bbcmicro.co.uk also doesn't do sound on iOS.

**Comment by mattgodbolt** [comment]
Thanks! Me too!

iOS doesn't have sound as the browser requires some kind of interaction
before it gives sound access:
https://gist.github.com/kus/3f01d60569eeadefe3a1 is a workaround.

**Comment by mattgodbolt** [comment]
I've arranged to borrow a Mac laptop over the next few days. Hopefully I
can figure out how to use it and then how to fix the issue!

**Comment by mattgodbolt** [comment]
No sign of the Mac as yet...hoping to get it in the next few days..

**Comment by BigEd** [comment]
Just seen this. In Safari 9.1.2 I find, in a fresh invocation:
- beta code does disk noises but no V.7 beep
- released code fails to boot the Beeb - blank screen. Console says
ReferenceError: Can't find variable: typeOf
in main-9a...b4.js line 10209

**Comment by mattgodbolt** [comment]
Thanks Ed!

The main site is broken (for sure); the beta site is indeed suffering from
no Beeb noises for reasons I can't fathom without access to a Mac. I'm
hoping to borrow one in the next few days and I'm sure it's just a simple
typo! The change I suspect is
https://github.com/mattgodbolt/jsbeeb/commit/2a5c21c6c336d1dd95444438f72c5659a3606d12
which
has a lot of things but the main bit is now I'm mixing the disc drive
sounds with the BBC audio using the JS API to do so. It *ought* to
work...but clearly doesn't!

**Comment by BigEd** [comment]
If there's anything I can try which will help, let me know.

**Comment by mattgodbolt** [comment]
Thanks mate! Are you up to setting some Javascript breakpoints? ANd/or is
there anything broken-looking in the Javascript console output on the beta
site?

**Comment by BigEd** [comment]
(I've sent you a mail)

**Comment by mattgodbolt** [comment]
Hi all: I've just got a Mac and was able to reproduce the issue...once! After setting up the Development menu to start debugging I reloaded and...the problem went away!

Can you guys checkout the https://bbc.godbolt.org/beta site and see if it's 100% failing on sound for you, or if it's intermittant? I'll investigate more when I get home tonight.

Thanks!

**Comment by ahope1** [comment]
100% failing. No sound (except for disc drive noise).

**Comment by mattgodbolt** [comment]
Thanks Ant...I will dig further..maybe enabling the debug menu "fixes"
it... (do you have "Show develop menu" enabled in the advanced preferences?)

**Comment by ahope1** [comment]
Yes, I do.

**Comment by ahope1** [comment]
What I have just noticed, though, is that the startup beep seems to be random: sometimes it beeps on startup, and sometimes it doesn't. 

But either way, there's then never any further sound (except drive noise).

**Comment by BigEd** [comment]
For me, fresh invocation of safari: no startup beep. Disk noise OK. No V.7 beep.
In a new tab: same.
Refresh the tab: same.

**Comment by mattgodbolt** [comment]
Ok. So this should now be fixed: I'd appreciate a quick try on https://bbc.godbolt.org/beta

In particular:

* Check normal sounds work (beeps etc)
* Check disc drive sounds work, and that you can hear the drive spinning noise OK

The error turned out to be what seems to be a Webkit audio bug where the "audio" objects aren't considered to be "live" by the garbage collector. The hack I had previously put in stopped working (presumably some optimization pass took out the apparently unused local variable...) and so  Ihad to fix it a different way. Dreadful, reall.

If I get the thumbs up I'll merge into the main site! Thanks!

**Comment by ahope1** [comment]
Works for me! Normal sounds and drive noises both play now. Thanks for looking into this!

**Comment by mattgodbolt** [comment]
Fantastic! Thanks for your help and patience while I work it out!

**Comment by mattgodbolt** [comment]
I've now updated the main site with all the fixes. Thanks again everyone!
