### ISSUE TITLE
In OS X Safari, file chooser won't select local .SSD 

### ISSUE THREAD

**Issue by ahope1** [mattgodbolt/jsbeeb#121]
When you select the "From examples or local" option in the Discs menu in JSBeeb in the Safari browser (v9.1.2) on OS X (v10.10.5), the file chooser window comes up, but everything is greyed out! So you can't select a .SSD (or .ssd) or a .DSD (or .dsd) to upload.

It works in Chrome on the same OS. Perhaps that's because in Chrome there's a drop-down list which is set to "Custom files" (the other option being "All files"), whereas in Safari there's no such drop-down control.

**Comment by mattgodbolt** [comment]
Thanks for the report: I think I know what this one is. I try to set a filter in the file picker for disc images `("<input type="file" id="disc_load" accept=".ssd,.dsd,image/*">")` but I wonder if that doesn't work properly...my HTML-fu isn't much good here.

**Comment by mattgodbolt** [comment]
can you try this: https://jsfiddle.net/Lkompv4t/ and see if either of the file pickers on the bottom right work for disc images?

**Comment by ahope1** [comment]
The second picker works for me -- although it allows me to select any file of any type!

The first doesn't let me select any file of any type.

**Comment by mattgodbolt** [comment]
Curious! On Chrome on Linux the second one lets me pick only DSDs and SSDs
unless I go to the filter at the bottom right of the OS file chooser and
say "All file types". I guess being able to pick everything is better than
picking nothing? Can you compare in OSX Chrome?

**Comment by ahope1** [comment]
In Chrome, both pickers work, both pickers let me choose only DSDs and SSDs unless I select "All files" in the drop-down list control. 

Safari doesn't display a list control in either picker.

**Comment by mattgodbolt** [comment]
I think I'll update the jsbeeb one to be like the second one then...at
least it'll work in Safari to pick disc images (or word documents...or text
files...or anything, but hey!) :)

Thanks!

**Comment by mattgodbolt** [comment]
I've pushed the fix to both the beta site and main public site. Hopefully that fixes it well enough!
