### ISSUE TITLE
Autoboot fails in latest version of JSBeeb, works in earlier version

### ISSUE THREAD

**Issue by ahope1** [mattgodbolt/jsbeeb#125]
The specified .SSD disc image of Terra Australis (Jacaranda Software) works in the earlier version of JSBeeb installed at bbcmicro.co.uk --

http://bbcmicro.co.uk/jsbeeb/?autoboot&disc=https://dl.dropboxusercontent.com/s/t4t55k1ukf1hqbt/TERRAA.SSD

-- but fails in the one that's currently live at bbc.godbolt.org:

http://bbc.godbolt.org/?autoboot&disc=https://dl.dropboxusercontent.com/s/t4t55k1ukf1hqbt/TERRAA.SSD

Looks like it's just the title screen that fails. The game goes on to load if you press SPACE at the blank screen.

**Comment by mattgodbolt** [comment]
Wow! Thanks for the headsup on this one, very weird. I don't know the exact version on bbcmicro.co.uk, but I'll do a `git bisect` to find where it changed.

**Comment by mattgodbolt** [comment]
The offending change was 2a5c21c6c336d1dd95444438f72c5659a3606d12 which is the one that introduces disc drive noises. So, as part of that, the disc loads slowed down: they're now synchronised with the sounds (the WAVs that is). I wonder what could be going on that the disc timings would affect the correctness so?

Weirdly when I see where it's stuck, it's in OSRDCH (`0xe53c` et al). @richtw1 do you have any wisdom on this? (to see where it's wedged follow the latter link and then hit ctrl-home)...

**Comment by mattgodbolt** [comment]
Oh; I've just seen your note about space: yes it does load OK after that! I wonder what on earth's going on that the disc load time causes the screen to be blank!

**Comment by richtw1** [comment]
Don't know, but more weird is that if you then Shift+Break again, it 
loads fine!

**Comment by ahope1** [comment]
It also works if you don't autoboot JSBeeb but load the disc image from a local file instead and then do Shift+Break.

**Comment by mattgodbolt** [comment]
We've had stuff like this before; a timing issue shown up because jsbeeb autoboot is 100% deterministic. I'll dig s little more when I get time.

**Comment by ahope1** [comment]
I was able to get the loading screen to display in JSBeeb on bbc.godbolt.org by altering the !BOOT file: I changed the last line from **_CH."INTRO"_** to **_CLOSE#0:CH."INTRO"_**. Here's the result:

http://bbc.godbolt.org/?autoboot&disc=https://dl.dropboxusercontent.com/s/7s7px1ts5oggqx8/TERRAA%20copy2.SSD

I was then able to reproduce the failure condition by deleting the **_CLOSE#0:_** again:

http://bbc.godbolt.org/?autoboot&disc=https://dl.dropboxusercontent.com/s/405g2203hqzgxtw/TERRAA%20copy3.SSD

I realise it might not specifically be the new command that makes it work, but perhaps just the extra time-cycles that are needed to execute it?

**Comment by ahope1** [comment]
Yes, looks like it's just adding a time delay that's the key, not the specific command that you add to the !BOOT:

http://bbc.godbolt.org/?autoboot&disc=https://dl.dropboxusercontent.com/s/ozzyt8i8vs31jhf/TERRAA%20copy4.SSD

There I just added a pointless PRINT statement.

**Comment by ahope1** [comment]
Don't know if this is related, but there seems to be a bug in the _older_ version of JSBeeb on bbcmicro.co.uk that stops you getting past the first menu in Space Warp:

http://bbcmicro.co.uk//jsbeeb/?autoboot&disc=http://bbcmicro.co.uk//gameimg/discs/Disc077-SpaceWarp.ssd

**Comment by ahope1** [comment]
@mattgodbolt If you get time to work on JSBeeb over Christmas, could you perhaps take a look at this issue? It's almost a showstopper because the bug can be triggered by any (totally legit) !BOOT that happens to be short/fast enough, and the game in question will then fail to load. 

(Oh, and another cheeky/pushy request: re disc-drive sounds, could we have an option to switch them off?! They really seem to slow down the loading of big games. E.g. see Dunjunz!)

Thanks for the incredible feat that is JSBeeb, and merry coding!

**Comment by mattgodbolt** [comment]
Hi!

Thanks for the kind words. I'm still not quite sure what's going on with
the load sequence causing some games to hang. I can definitely make disc
noises optional (and a little shorter anyway!)

Do you have any ideas what might cause the boot hang? I am reluctant to
"just" speed up disc reads without understanding it just for its own sake
but I also appreciate having working games :/)

**Comment by ahope1** [comment]
Lawks, I wish I knew! I fear I don't know quite enough about either the Beeb or JavaScript to be able to even speculate about the cause of the hang!

I do agree that the issue needs to be understood first though!

**Comment by ahope1** [comment]
Another game that fails to autoboot:

[http://www.stardot.org.uk/forums/viewtopic.php?f=51&t=12387&p=172173#p172172](http://www.stardot.org.uk/forums/viewtopic.php?f=51&t=12387&p=172173#p172172)

**Comment by mattgodbolt** [comment]
Thanks for the update, and for posting a possible workaround on stardot! I really don't know what might be going on here...

**Comment by ahope1** [comment]
Can you debug the JSBeeb VM and see what it's actually doing when it hangs on autoboot?

**Comment by mattgodbolt** [comment]
Yes; is super time consuming though. Hit ctrl-HOME to enter the debugger...

Last time I spent ages finding something like this it was a long-standing
bug in the emulated software that was just deterministic with an emulator
:) https://xania.org/201410/debugging-with-jsbeeb for one war story

**Comment by scarybeasts** [comment]
@mattgodbolt @ahope1 this seems to work for me, looks like something fixed it? Can we close?

**Comment by lurkio** [comment]
> @mattgodbolt @ahope1 this seems to work for me, looks like something fixed it? Can we close?

Looks like the Terra Australis disc-image in question does indeed work in the latest version of JSBeeb at bbc.godbolt.org:

http://bbc.godbolt.org/?autoboot&disc=https://dl.dropboxusercontent.com/s/t4t55k1ukf1hqbt/TERRAA.SSD

**Comment by mattgodbolt** [comment]
Great stuff! Closing :) thanks both!
