### ISSUE TITLE
Please add a 6845 debug window similar to the VIA one

### ISSUE THREAD

**Issue by richard-broadhurst** [mattgodbolt/jsbeeb#131]
Please add a 6845 debug window similar to the VIA one with whatever state the emulator is using.
All the registers and the current internal values.
e.g. scan out pos, digital version of the glowing circle.
e.g. current horizontal character, line of v-adjust etc.

**Comment by mattgodbolt** [comment]
Take a look at http://bbc.godbolt.org/beta/ and see if there's anything missing from the registers and internals listed at https://github.com/mattgodbolt/jsbeeb/blob/master/video.js

**Comment by richard-broadhurst** [comment]
That is just what I wanted, unfortunately it hasn't helped me fix my bug :(
I'm getting vertical jitter of one scan line every so often and
occasionally the wrong bit of screen displayed.
It seems from the debug that the vertical position of my interrupts is
exactly where I am expecting it, but still it looks like my timing is
unreliable - I've probably just overwritten something somewhere, but I
can't think where!

**Comment by mattgodbolt** [comment]
Good luck tracking the bug: let me know if I can do anything else here. And of course; don't forget to suspect jsbeeb's emulation as being the culprit too!
