### ISSUE TITLE
Possible bug with video address calculation in linear scan mode

### ISSUE THREAD

**Issue by richard-broadhurst** [mattgodbolt/jsbeeb#132]
I could be wrong as I'm away at the moment and don't have a beeb here and both beebem and b-em seem to get this wrong.

On a real beeb, setting R12/R13 start of display address gives the following results:
http://www.retrosoftware.co.uk/forum/viewtopic.php?f=73&t=1011&p=7920&hilit=%263c00..#p7729

&2000..&23FF displays &3C00+R12R13 wrapping after &3FFF to &3C00
&2400..&27FF displays &3C00+R12R13 wrapping after &3FFF to &7C00
&2800..&23FF displays &7C00+R12R13 wrapping after &7FFF to &7C00
&2B00..&23FF displays &7C00+R12R13 wrapping after &7FFF to &3C00

I don't have my original test app, but this might be OK.
   10 *K.10O.|MREN.|ML.|M
   20 MODE 7
   30 DIGIT$="0123456789ABCDEF"
   40 FOR X%=&3C00 TO &3FFF STEP 4
   50 PROCSET
   60 X%=X%+&4000
   70 PROCSET
   80 X%=X%-&4000
   90 NEXT
  100 Y%=&20
  110 REPEAT
  120 ?&FE00=12:?&FE01=Y%
  130 Y%=Y%+1
  140 A$=GET$
  150 UNTIL0
  160 DEFPROCSET
  170 X%?0=ASC(MID$(DIGIT$,1+(X% DIV &1000),1))
  180 X%?1=ASC(MID$(DIGIT$,1+((X% DIV &100) AND &F),1))
  190 X%?2=ASC(MID$(DIGIT$,1+((X% DIV &10) AND &F),1))
  200 X%?3=ASC(MID$(DIGIT$,1+(X% AND &F),1))
  210 ENDPROC
Press any key to advance the start address by &100.

**Comment by mattgodbolt** [comment]
Thanks for the comprehensive bug report! @richtw1 ; any words of wisdom on this?

**Comment by mattgodbolt** [comment]
Just read the linked forum posts; I think I get it now...and that there's a Beeb/Master difference which is why me and @richtw1 [who both had Masters BITD] would initially think "that's not how it works!"

**Comment by richard-broadhurst** [comment]
To put it in a bit more context, I was playing with the idea of two scan-line high pixels and various combinations of "chunky" graphics and mode 7 text.
http://stardot.org.uk/forums/viewtopic.php?f=1&t=11884&start=30#p151676
I think you should also be able to do a 128x128 mode 5 in 2K or even a 64x64 mode "8" in 1K (pallette timing allowing). A pity they didn't connect one more bit allowing a 128x128 mode 2 4K layout.

**Comment by richard-broadhurst** [comment]
Sorry, my maths are of by 2x, but I think the behaviour as you say is master not model b.
