### ISSUE TITLE
JSBeeb fails in Safari 10.0

### ISSUE THREAD

**Issue by ahope1** [mattgodbolt/jsbeeb#133]
The latest version of Safari on OS X (I'm on OS X 10.10.5 Yosemite) won't run JSBeeb at all. JSBeeb won't boot. You just get the Cub monitor frame with a black, empty "screen" inside. This is true both for the version at bbc.godbolt.org and for the one at bbcmicro.co.uk.

**Comment by ahope1** [comment]
Oops. My mistake. I needed to reboot. Sorry.

**Comment by mattgodbolt** [comment]
That's odd! If it happens again, please have a look at the JavaScript
console and post here what you see. Thanks!
