### ISSUE TITLE
Is the lightpen interrupt modelled?

### ISSUE THREAD

**Issue by BigEd** [mattgodbolt/jsbeeb#135]
I tried and failed to run Pharaoh's Curse [here](http://bbcmicro.co.uk/jsbeeb/play.php?autoboot&disc=http://bbcmicro.co.uk/gameimg/discs/Disc027-PharaohsCurse.ssd) - the game hangs to a black screen at the point I'd expect it to draw the playfield.

I wonder if that's anything to do with the lightpen interrupt, as mentioned [here](http://stardot.org.uk/forums/viewtopic.php?p=32556#p32556):
"On the Beeb you can trigger a 'fake' light pen interrupt, which makes the CRTC latch the current video address into the light pen registers. Handy for synchronisation. Beebem doesn't emulate this though, only B-em and BeebinC do."

There are other tricky games mentioned in [this thread](http://stardot.org.uk/forums/viewtopic.php?p=86252#p86252).

**Comment by mattgodbolt** [comment]
Nice! It's not modelled...but it should be! Thanks for the handy information here!

**Comment by scarybeasts** [comment]
Ah, there seem to be two different games called Pharaoh's Curse? The attached file is the one we're talking about here and it's a version without the problem code hacked out, so it still fails in jsbeeb.

[PharaohsCurse.zip](https://github.com/mattgodbolt/jsbeeb/files/3475158/PharaohsCurse.zip)

I will fix.

**Comment by mattgodbolt** [comment]
Thanks @scarybeasts

**Comment by scarybeasts** [comment]
Follow on PR https://github.com/mattgodbolt/jsbeeb/pull/209 sent to do the light pen handling without incurring cost in the main polltime() loop.
