### ISSUE TITLE
Oddjob game fails

### ISSUE THREAD

**Issue by ahope1** [mattgodbolt/jsbeeb#136]
http://bbcmicro.co.uk/jsbeeb/play.php?autoboot&disc=http://bbcmicro.co.uk/gameimg/discs/Disc103-OddJobD.ssd

The game fails with a "Bad program" error at the loading screen. Fails in the version of JSBeeb at godbolt.org too. But the same disc image works in BeebEm.

**Comment by mattgodbolt** [comment]
I just tried in b-em (v2.2) and the same thing happens: `Bad Program` at the same point as jsbeeb. Did Oddjob run reliably on a real Beeb?  What version of BeebEm are you using? I can try comparing the two to see what the difference is.

**Comment by ahope1** [comment]
I'm using the latest official Windows version of BeebEm. 

Not sure if this disc image of Oddjob runs reliably on a real Beeb. I'm away from all my Beebs at the mo, so can't test. Do you have a Beeb you could test on yourself?

**Comment by mattgodbolt** [comment]
Sadly I don't have a Beeb with me (mine are 4000 miles away in my
attic...). I will grab a Linux version of BeebEm and see if I can work out
what might be going on.

**Comment by ahope1** [comment]
Ah. Hold your horses. I just asked someone to check the disc image by exporting it to a real floppy and booting it on a real Beeb, and he got the same "Bad program" error!

**Comment by ahope1** [comment]
Release the horses again! It turns out that on a real floppy in a real Beeb, the disc image fails in DFS 0.9 but works in DFS 1.2.

**Comment by richtw1** [comment]
Yeah, I was going to suggest it was a DFS version thing.  It looked as 
if some of the DFS workspace in page &10 was being trampled by the 
code.  So I think this is a bug in the game, not in jsbeeb.

**Comment by mattgodbolt** [comment]
Thanks @richtw1 and @ahope1 ; that's one fewer thing to worry about. I need a way to select BBC Models with more fidelity to allow this to run.
