### ISSUE TITLE
Better model selection

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#137]
More customization of the emulation environment, specifically:

* which DFS/hdc controller
* sideways RAM
* extra ROMs

Some games fail under certain DFS versions (e.g. #136)

**Comment by ahope1** [comment]
Yes, I'd say that adding the ability to select DFS 1.2 should be a priority here. 

In fact, you might want to consider making DFS 1.2 the default. I know there's a theory that DFS 0.9 is compatible with more games, but I've never had a problem with 1.2 in BeebEm. I don't know of any games that work only with DFS 0.9. 

Perhaps Rich has some concrete examples of games that fail with 1.2 but work with 0.9..?

**Comment by scarybeasts** [comment]
Let's use this bug to track adding a new model that has a DFS compatible with the known instances of images that are _not_ DFS-0.9 compatible.

We could just add a DFS 1.2 model of course. But I think it may be a better option to add an E00-DFS model as our first addition. Here is my reasoning:
- The images I know of that require DFS-1.2 (Puff, OddJob) also work fine with an E00 DFS.
- E00 DFS resolves at least one problem that DFS-1.2 doesn't: EliteA is a bit buggy and if you manage to launch the main game before the disc spins down, it won't work with DFS-0.9 or DFS-1.2. E00 DFS is fine.
- There are quite a number of images in the STH archive, with E00 in their name, that _require_ an E00 DFS and many of them don't have a non-E00 counterpart.

@mattgodbolt What are your thoughts on adding MRM software's E00 DFS?
http://mdfs.net/System/ROMs/Filing/Disk/Others/E00DFS.TXT

Do you think the copyright will have expired on that one, similar to the Acorn ROMs?

**Comment by richtw1** [comment]
Honestly I wouldn't add a non-standard DFS.  Any images which require an E00-DFS wouldn't have worked on real standard hardware at the time, and I don't see a big reason to support them under emulation (and presumably they work OK in Master mode?).

I'd be inclined just to change from DFS 0.9 to 1.2, now that the 8271 emulation is better.  Adjusting the emulator spec to work around bugs in old disk images still seems like the wrong approach to me.

**Comment by scarybeasts** [comment]
Ok, I can lay the groundwork for trying DFS-1.2 by default.
