### ISSUE TITLE
Huge performance regression in Chrome 55

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#138]
Having just reinstalled Linux and installed the latest Chrome, I'm seeing a gigantic performance regression in Chrome 55.

A profile seems to suggest it's `video.clearFb` that's to blame, and indeed commenting out that routine yields a huge speedup (virtual 1.5MHz to 6Mhz on my machine, back to pre-reinstall speed). Rephrasing the routine in multiple ways (a vanilla `for`, unrolling...) doesn't appear to help.

**Comment by mattgodbolt** [comment]
Super-curiously, if I replace the code with `this.blitFb8(0, destoffset, false)` it still runs fast. So the `blit` functions work faster...

**Comment by mattgodbolt** [comment]
Even this doesn't improve matters - I wonder what on earth is going on. This is basically a port of blitFb but with a constant value on the right-hand side of the assignment!

```javascript
        this.clearFb8 = function (destOffset) {
            var fb32 = this.fb32;
            destOffset |= 0;
            fb32[destOffset] = 0xff000000;
            fb32[destOffset + 1] = 0xff000000;
            fb32[destOffset + 2] = 0xff000000;
            fb32[destOffset + 3] = 0xff000000;
            fb32[destOffset + 4] = 0xff000000;
            fb32[destOffset + 5] = 0xff000000;
            fb32[destOffset + 6] = 0xff000000;
            fb32[destOffset + 7] = 0xff000000;
        };
        this.clearFb = function (destOffset, numPixels) {
            this.clearFb8(destOffset);
            if (numPixels === 16)
                this.clearFb8(destOffset + 8);
        };
```

**Comment by mattgodbolt** [comment]
Changing the above modification to:
```javascript
        this.clearFb = function (destOffset, numPixels) {
            this.blitFb8(0, destOffset, false);
            if (numPixels === 16)
                this.blitFb8(0, destOffset + 8, false);
        };
```
Yields back the performance. Utterly bewildering.

**Comment by mattgodbolt** [comment]
In a non-very-scientific test I checked on my work laptop (Chrome 54) and it sees a 10MHz virtual CPU (it's a faster than this laptop, but not my a huge amount). That seems to indicate it really is a Chrome 55 change. I'll see if I can find a way to get 54 on this laptop to test like with like. But it seems tricky to downgrade.

**Comment by BigEd** [comment]
If you run the Canary build on the work laptop, that should give you two versions you can run in parallel.
https://www.google.co.uk/chrome/browser/canary.html
Or, there are deep archives of the Chromium Nightly Builds online. See
https://www.chromium.org/getting-involved/download-chromium

**Comment by mraleph** [comment]
@mattgodbolt btw it's unclear how to reproduce the regression could you provide step by step guide at what to run and where to for FPS counter?

**Comment by bmeurer** [comment]
You could help us a lot by reducing the repro to a simple page, ideally with a single JS function that runs slow vs. fast.

**Comment by BigEd** [comment]
I noticed the Beeb's excellent typeahead has been really poor recently, and just checked, learning that Chrome 55 has the problem, and 57 does not. I also checked Firefox 46 and Safari 9.1.3 on the same machine, and both are fine.

**Comment by bmeurer** [comment]
Interesting, can you try with 56 too?
If you're right, then there's some performance fix in canary/dev that we should back-merge to 55 (and maybe 56).

**Comment by BigEd** [comment]
Running the Beta version, which is a 56, seems fine.

**Comment by mattgodbolt** [comment]
Hi all; apologies for being away. Thanks for taking a look at this. I'll try and get a much smaller repro: I was in a hurry to file the bug last night before going out!

**Comment by mattgodbolt** [comment]
Ok I've made a much simpler (though not totally minimal) test case. Sadly not on any live site, you'll need to `git clone` and run locally. But, visit `perf-test.html` and you'll see:

## Chrome 55
```Took 928ms to do 500000 16 32-bit clears```

## Chrome 56.0.2924.1
```Took 28ms to do 500000 16 32-bit clears```

I hope this minified test is easier to look in to. Thanks so much!

**Comment by mattgodbolt** [comment]
I've actually made the whole test standalone. It now runs directly from http://bbc.godbolt.org/beta/perf-test.html and the entire code is
```javascript
function tst(fb32, destOffset, numPixels) {
    var black = 0xFF000000;
    while (numPixels--) {
        fb32[destOffset++] = black;
    }
}
var fb32 = new Uint32Array(1024);
var reps = 500000;
var start = Date.now();
for (var i = 0; i < reps; ++i)
    tst(fb32, 0, 16);
var end = Date.now();
var result = "Took " + (end - start) + "ms to do " + reps + " 16 32-bit clears";
console.log(result);
```

So hopefully that makes it even simpler to find.

**Comment by BigEd** [comment]
Just to note, on my Chromebook which seems to be on Chrome 54, I get a fast result:
Took 55ms to do 500000 16 32-bit clears
And typeahead is OK.
(Intel(R) Celeron(R) CPU N2840 @ 2.16GHz)

**Comment by natorion** [comment]
Culprit identified (https://bugs.chromium.org/p/chromium/issues/detail?id=666947). The fix should be on the next 55 push.

**Comment by mattgodbolt** [comment]
Fantastic! Thank you so much for the extremely quick turn-around on this! And on a weekend!
