### ISSUE TITLE
*COPY to a local disc doesn't work reliably

### ISSUE THREAD

**Issue by ahope1** [mattgodbolt/jsbeeb#139]
If you start JSBeeb with a remote disc in the first drive and a local disc in the second, the DFS command `*COPY 0 1 *.*` doesn't reliably copy the contents of all the files onto the local disc. All the catalogue entries seem to be created, but some of the files on the local disc just contain a string of zero-bytes instead of the contents of the original files.

**Comment by scarybeasts** [comment]
@ahope1 Does this still reproduce for you? If so, can you give an example launch URL that sets up jsbeeb as you describe? Seems like something I could try and fix.

**Comment by ahope1** [comment]
> @ahope1 Does this still reproduce for you? If so, can you give an example launch URL that sets up jsbeeb as you describe? Seems like something I could try and fix.

@scarybeasts Yes, if you use the link below and do the `*COPY 0 1 *.*` and wait for the copy to finish, you can then do `*DRIVE 1` and `*DUMP !BOOT`, and you'll see that the !BOOT file is all zeroes! Other files are just zeroes too. It seems to be the files towards the end of the disc that are affected.

https://bbc.godbolt.org/?disc2=local:YYY

**Comment by scarybeasts** [comment]
Oh thanks @ahope1 !

Good news, easy to fix.
Bad news, I think @mattgodbolt owes us both a beer for this one! PR incoming...

**Comment by mattgodbolt** [comment]
Uh oh... add it to the tally @scarybeasts :D
