### ISSUE TITLE
Difference in MODE 7 Hold Graphics support vs real hardware

### ISSUE THREAD

**Issue by kieranhj** [mattgodbolt/jsbeeb#141]
The attached ssd [mode7-bug.zip](https://github.com/mattgodbolt/jsbeeb/files/714908/mode7-bug.zip) contains some MODE 7 frames auto-generated from my slightly dodgy image converter which has a tendency to produce odd sequences of Hold + Release Graphics characters.  For example, the red parrot image appears to be "correct" in jsbeeb but looks like this on real hardware:

![bbc_parrot_gaps](https://cloud.githubusercontent.com/assets/17362752/22080927/66e78e62-ddb9-11e6-93ba-159a8ce01a70.jpg)

Hold Graphics is generally considered arcane so I am soliciting more information from some Teletext experts, mostly @rawles author of https://github.com/rawles/edit-tf.

**Comment by scarybeasts** [comment]
@kieranhj @mattgodbolt Looks perfect to me in the latest version currently hosted on https://bbc.godbolt.org/

I did suck at those "spot the difference" things as a kid though.

Can we close?

**Comment by mattgodbolt** [comment]
![Screenshot from 2019-08-07 07-31-39](https://user-images.githubusercontent.com/633973/62623050-7915bc80-b8e5-11e9-9c88-27a02122a956.png)

This is what the current image looks like. @kieranhj can you see any differences? Thanks!

**Comment by scarybeasts** [comment]
One thing to note is that Kieran skillfully arranged the cursor to be at the very bottom in his screenshot. For an apples to apples test you may need to scroll the cursor down (enter enter enter.... etc.) to one line before the bottom and then type *LOAD RED

**Comment by scarybeasts** [comment]
I'm going to go out on a limb and close this as fixed.
This bug was filed Jan 2017 and there's a commit from Tom Seddon in Nov 2017 entitled "Fix hold mosaics processing.": https://github.com/mattgodbolt/jsbeeb/commit/e309fceaa058a0c7e41e0250494d22f75921eefe#diff-fe97883998e9c7af7d6c87d2948ba529

I reverted that change on a local branch and it breaks the parrot a little bit: the black boxes in the yellow part of the head go missing.

**Comment by hoglet67** [comment]
Here's another sequence that doesn't quite work correctly:

VDU &91,&61,&9E,&92,&93,&94,&81,&91,&91,10,13

The &81 should reset the held character to a space, and to that as "set after". On JSBeeb the held character remains.

![Screenshot from 2021-02-06 10-51-36](https://user-images.githubusercontent.com/1951463/107116166-5d3bff80-6869-11eb-8735-cfafd6360ee7.png)

Here's the read hardware:
![capture3](https://user-images.githubusercontent.com/1951463/107116220-96746f80-6869-11eb-8a40-29af0fd5e2d7.png)

**Comment by BigEd** [comment]
(@scarybeasts  should this be reopened? Or a new issue?)

**Comment by scarybeasts** [comment]
This issue's a bit long in the tooth; I'd recommend a new issue.

**Comment by hoglet67** [comment]
Opened a new issue: #316

**Comment by mattgodbolt** [comment]
Thanks folks!
