### ISSUE TITLE
256 byte transfer over Tube hangs on Tube release call

### ISSUE THREAD

**Issue by kieranhj** [mattgodbolt/jsbeeb#142]
Boot the attached ssd [tube-bug.zip](https://github.com/mattgodbolt/jsbeeb/files/715171/tube-bug.zip) in Master Turbo mode. In MODE 7 you should see a message on screen, in any other mode a flash of green raster and then some crap left in the screen buffer.

This is copying 256 bytes from the parasite RAM over to the host RAM using the 256 byte "fast" transfer protocol - see AUG page 338 for details.

Alas on jsbeeb (and B-Em) the Tube code hangs during the Tube release call waiting for a byte from the parasite that never arrives.  This has been verified to work on my actual Master Turbo hardware.

**Comment by mattgodbolt** [comment]
Thanks @kieranhj :) -- tube support is super dodgy: Tube Elite works for a bit then goes wrong... #44 for example.  This is an awesome simple test case I can try to fix: thanks!

**Comment by kieranhj** [comment]
No worries Matt. Trying to write a copro demo but slow to dev without good emu support. There are more details from JGH on the Tube timing requirements in this thread: http://stardot.org.uk/forums/viewtopic.php?f=54&t=12425

**Comment by kieranhj** [comment]
This was a trivial fix for b-em. I would submit a PR but I don’t have a suitable build environment to test!

https://github.com/kieranhj/b-em-1/commit/a7a7d83abfc72f76dc435fea63adea56a1708d72

**Comment by mattgodbolt** [comment]
Thanks Kieran! We can work from this!
