### ISSUE TITLE
OpenGL canvas no longer works...

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#143]
on Chrome 56 at least:
```
Unable to use OpenGL: Error: Unable to create a GL context```

**Comment by scarybeasts** [comment]
Many Chrome versions later but Chrome 76 seems fine with latest https://bbc.godbolt.org/

@mattgodbolt How is it for you, can we close?

**Comment by mattgodbolt** [comment]
Oh cripes, this is ancient. Thanks for doing the spring cleaning of the bug list!
