### ISSUE TITLE
feature request - Drag and drop file loading

### ISSUE THREAD

**Issue by BigEd** [mattgodbolt/jsbeeb#146]
Norbert Landsteiner has just implemented drag and drop file loading in his JS PET emulator, and it's great!
Announcement: https://plus.google.com/+NorbertLandsteiner1/posts/T1soB3ZJ1xN
Emulator: http://www.masswerk.at/pet/

**Comment by mattgodbolt** [comment]
Awesome idea! thanks!

**Comment by scarybeasts** [comment]
I've implemented this because it's a great time saver for me :)

For posterity, it's worth noting that the incoming PR also fixes loading of DSDs from the STH archive, which was surprisingly broken -- Lancelot.zip for example contains a DSD and won't load currently.

**Comment by mattgodbolt** [comment]
Great stuff! thanks @scarybeasts . FWIW I typically dump DSDs into the `discs/` directory (which is set up to ignore new things in `git`, so they don't get added...then I use urlparams to quickly re-test discs etc. This is a welcome addition!
