### ISSUE TITLE
uridium is stuck in demo mode

### ISSUE THREAD

**Issue by BigEd** [mattgodbolt/jsbeeb#152]
please see this thread
http://stardot.org.uk/forums/viewtopic.php?p=184566#p184566

(Still might be user error, but affects two people, and apparently the SSD is good on other emulators)

**Comment by BigEd** [comment]
Sorry bit of a dupe of #130

**Comment by scarybeasts** [comment]
Thanks for filing this @BigEd 

There are definitely at least two problems here with jsbeeb and Uridium. The "stuck in demo mode" is a distinct issue when running with the master model. It is related to CMOS handling I think.

**Comment by scarybeasts** [comment]
I will try and fix it.
