### ISSUE TITLE
Fortress (Tape Version) crashes while loading

### ISSUE THREAD

**Issue by PeterBBCUser** [mattgodbolt/jsbeeb#153]
Fortress Tape version crashes out into debug while loading the data block at the end, see the following screen shot :-
http://www.stardot.org.uk/forums/download/file.php?id=33539&t=1

**Comment by mattgodbolt** [comment]
Oh blast; thanks for the heads up.

**Comment by PeterBBCUser** [comment]
It's not a train smash just though I would let you/others know.
This was the screen shot had 1st posted a link to it at STH.
![image](https://user-images.githubusercontent.com/33581895/33232972-a83cc53a-d20f-11e7-9301-143474137f06.png)

**Comment by PeterBBCUser** [comment]
o Just tried it with the tape copy on STH https://bbc.godbolt.org/?tape=sth%3APace%2FFortress_B.zip# and that one works fine how odd.

**Comment by PeterBBCUser** [comment]
okay so my copy I have (made from an original tape) is not good..... but it still should not crash the emulator as it does
[FortressSide1_8Bit.hq.zip](https://github.com/mattgodbolt/jsbeeb/files/1503302/FortressSide1_8Bit.hq.zip)
Hear is a copy of the faulty fortress which crashes the emulator.
.

**Comment by mattgodbolt** [comment]
Agreed! Taking a look - thanks for the copy

**Comment by mattgodbolt** [comment]
Did the emulator crash and pop up the debugger in the screenshot? Or had you hit ctrl-home to bring it up?

I loaded the UEF you linked and I get to the `Found: ***********` screen, but the emulator is still running. Admittedly the game hasn't started up, it's stuck on that screen (which an only be an emulation bug); but I wanted to be sure I was seeing the same thing you were.

**Comment by mattgodbolt** [comment]
Hitting ctrl-HOME brings up the PC stuck in the same place as your screenshot, so i suspect that's the same thing you're doing.

In the uef I noticed a bunch of "defined data" and "security bits" sections - do you know if Fortress had any exotic tape protection? If so, it's probably the (lack of!) support for this in jsbeeb! Thanks :)

**Comment by PeterBBCUser** [comment]
I am using Firefox and it pops that up by itself at that point, the only protection is that the data has changing parity but as I said that copy was one I made from an original tape but it not right, the uef also does not work on another emulator just stops at that point but jsbeep throws up the debug screen by me.

**Comment by mattgodbolt** [comment]
Got it! I just realised it's a bug I've fixed in my local version but I haven't updated bbc.godbolt.org :grinning: ! That's why it didn't happen to me, but I was able to reproduce it on the website.

Updating now - thanks for the headsup!

**Comment by PeterBBCUser** [comment]
Ahh that explains why you did not see it, and thank you for a great online emulator:)

**Comment by mattgodbolt** [comment]
Thanks for taking the time to report the issue. I've uploaded the fixed version and while doing so noticed #154 - so it's all good news!
