### ISSUE TITLE
SOUND and ENVELOPE BASIC commands don't appear to work

### ISSUE THREAD

**Issue by bartread** [mattgodbolt/jsbeeb#158]
I tried out some of the `SOUND` and `ENVELOPE` commands at http://central.kaserver5.org/Kasoft/Typeset/BBC/Ch30.html but couldn't get any sound out of the emulator (apart from the beep on boot up).

This is using Chrome 61 on OSX.

**Comment by mattgodbolt** [comment]
Do you have an examples of what you tried? I tried:

`SOUND 1,-15,53,20`

And it worked exactly as I expected.

**Comment by mattgodbolt** [comment]
Closing, as no response, and I couldn't reproduce. Feel free to reopen if you still have an issue!
