### ISSUE TITLE
Simulated Shift keypress on autoboot is held for too long, disrupts paged scrolling

### ISSUE THREAD

**Issue by ahope1** [mattgodbolt/jsbeeb#166]
If you click on an autobooting JSBeeb link [like this one](https://bbc.godbolt.org/?autoboot&disc=https://dl.dropboxusercontent.com/s/f7zpglqfawowlqd/VDU14bug.ssd), which has a !BOOT that CHAINs a BASIC program that immediately uses VDU14 to activate paged scrolling mode (which requires the user to press Shift to scroll the screen in the emulated Beeb) before printing an infinite list of numbers, then the simulated Shift keypress (which I assume is JSBeeb's way of implementing a Shift-Break to boot the disc-image) is held for too long and causes the screen to scroll a couple of times when it shouldn't:

[https://bbc.godbolt.org/?autoboot&disc=https://dl.dropboxusercontent.com/s/f7zpglqfawowlqd/VDU14bug.ssd](https://bbc.godbolt.org/?autoboot&disc=https://dl.dropboxusercontent.com/s/f7zpglqfawowlqd/VDU14bug.ssd)

Try pressing Shift-Break to boot the disc-image manually to see the correct behaviour.

More details here:

[http://www.stardot.org.uk/forums/viewtopic.php?f=4&t=14581#p194938](http://www.stardot.org.uk/forums/viewtopic.php?f=4&t=14581#p194938)

**Comment by murkle** [comment]
Is this a problem given that " I've chosen to rework my program (an instructions displayer) and eliminate scrolling altogether!"

Suggested solution of checking for disc access doesn't seem very robust (eg with no DFS I think Shift-break works for Tape Filing System and (??) Rom Filing System)

**Comment by ahope1** [comment]
@murkle It's a problem in that it's not the behaviour that a user would expect. Also, not every disc ever made since the 1980s can easily be changed to work around this bug!

You can't Shift-Break a tape. Don't know about ROM FS. 

There's another suggested solution further down the thread:

http://www.stardot.org.uk/forums/viewtopic.php?f=4&t=14581&sid=cf775515a089016e56c624ee05b2dbb3#p194947

**Comment by richtw1** [comment]
In OS 1.20, the check for Shift held on reset happens at &DB87. The call to
set the keyboard LEDs calls KEYV to do a direct check for Shift and Ctrl
held (which is maintained in &25A).  Anyway, point is, Shift only needs to
be held high on autoboot until then.  I imagine 1/10th of a second after it
enters the reset code is more than enough.

Possible other things which might work
- Hold Shift high until the first time it's checked (unless there's an IRQ
routine which does this elsewhere)
- Wait until OSCLI called for first time with '/!BOOT' string

I'd just be inclined to really shorten the duration though. It has to get
past the memory clear and hardware initialization, which is a bit longer on
a Master. Maybe 1/5th of a second, playing it safe?

**Comment by scarybeasts** [comment]
Tentatively marking as closed / fixed. Please do feel free to reopen if you disagree.

Doesn't reproduce in latest https://bbc.godbolt.org.

I think what may have happened here is that my recent i8271 fixes fixed disc spinup. Previously, the seek timer would run in parallel with the spin timer, and depending on controller usage, data read commands could even kick off before spinup was complete. Now, no disc activity (seeks, reads or other) will occur before the 0.5s spinup is complete, which is likely enough to push the 1s shift hold timing into the "safe" zone.

**Comment by ahope1** [comment]
Yes, the bug doesn’t seem to be reproducible in the latest version of JSBeeb. 

Just for reference, here’s the bug in action in the older version of JSBeeb that’s currently still installed on bbcmicro.co.uk: 

http://bbcmicro.co.uk//jsbeeb/play.php?autoboot&disc=https://dl.dropboxusercontent.com/s/f7zpglqfawowlqd/VDU14bug.ssd

**Comment by mattgodbolt** [comment]
Thanks both!
