### ISSUE TITLE
Difference with CRTC vs real hardware

### ISSUE THREAD

**Issue by kieranhj** [mattgodbolt/jsbeeb#169]
I am currently developing a (potential) new demo that involves lots of CRTC abuse. :)
[twister.zip](https://github.com/mattgodbolt/jsbeeb/files/1896453/twister.zip) Runs on Master 128 only.

This uses the manual vsync approach that I thought I obtaiined from retrosoftware forums BITD but can't find the original reference anywhere. (My notes say maybe Tom Seddon & Tricky but might have been RTW?)

```
	{
		lda #2
		.vsync1
		bit &FE4D
		beq vsync1 \ wait for vsync
		\now we're within 10 cycles of vsync having hit


		\delay just less than one frame
		.syncloop
		sta &FE4D \ 4(stretched), ack vsync

		\{ this takes (5*ycount+2+4)*xcount cycles
		\x=55,y=142 -> 39902 cycles. one frame=39936
		ldx #142 \2
		.deloop
		ldy #55 \2
		.innerloop
		dey \2
		bne innerloop \3
		\ =152
		dex \ 2
		bne deloop \3
		\}

		nop:nop:nop:nop:nop:nop:nop:nop:nop \ +16
		bit &FE4D \4(stretched)
		bne syncloop \ +3
		\ 4+39902+16+4+3+3 = 39932
		\ ne means vsync has hit
		\ loop until it hasn't hit

		\now we're synced to vsync
	}
```

It then sets up the CRTC to use 1 scanline per character row and 1 character row per CRTC cycle then cycle counts to update the screen buffer address in CRTC R12/R13 every scanline. On scanline 255 it sets up the necessary registers to trigger vsync at the appropriate point and form a 312 scanline signal (at least in theory.)

However, since R12/R13 are only read on a new CRTC cycle, these are reset at the end of the frame (scanline 255) ready for scanline 0 after vsync. I've hacked the code so that the first scanline is a fixed address (&3000) and this is the result I see on jsbeeb (and b-em) but on real Master hardware the last scanline is fixed at the bottom of the screen?! This is on both a CUB monitor and a more modern LCD flatscreen via RGB SCART.

I'm confused what's happening here. It might well be user error (and a misunderstanding of PAL timings) or something else. I'm pretty sure I have interlace turned off on my machine.

Source is on GitHub [here](https://github.com/bitshifters/just-rasters) (although working versions may be lurking in branches.)

**Comment by mattgodbolt** [comment]
Thanks for the awesome report Kieran. Lurking on lists revealed this: http://www.6502.org/users/andre/hwinfo/crtc/index.html which might be useful when I get around to taking a look. Noting it here for now!

**Comment by kieranhj** [comment]
More discoveries related to this topic [here](https://stardot.org.uk/forums/viewtopic.php?f=4&t=14971&start=30#p204823).  Don't suppose you fancy a go at fixing this in time for the demo release at the end of the month?! 😁

**Comment by kieranhj** [comment]
OK, so seems more likely that the issue here is the exact time at which the CRTC checked the VerticalCharacterCount==R4. There is a simpler test example in the thread: https://stardot.org.uk/forums/viewtopic.php?f=4&t=14971&start=30#p205029

**Comment by mattgodbolt** [comment]
Just a minor update...happened to be poking about with b2 and we at least agree :) So, on a real Master the top line is part of the wiggly goodness, and the last line is the one with a fixed line? (I just see the fixed line at the top)

**Comment by scarybeasts** [comment]
@mattgodbolt @kieranhj I'm interested in taking a swing at this.

To confirm, is the attached screenshot representative of the glitch? I ran bs-twisted.ssd on latest jsbeeb, selected option "REAL HARDWARE", and see a clear incorrect scanline in some of the later effects.
![twisted](https://user-images.githubusercontent.com/26288899/62847591-f6e21b00-bc8b-11e9-9ec2-664a76afc1e1.png)

**Comment by scarybeasts** [comment]
Also -- does anyone have an SSD file for the minimized test case?

**Comment by mattgodbolt** [comment]
pinging @kieranhj here: I checked the stardot thread you mentioned and I'm blowed if I can see the minimal test case there :)

**Comment by kieranhj** [comment]
Hmm, not sure there is a minimised test case unless it was the twister.zip in the first post. I do have some test code somewhere but not currently able to fire up my real Master to check & describe. Probably be this time next week, sorry.
