### ISSUE TITLE
Runs slowly when palette is changed many times per line

### ISSUE THREAD

**Issue by VectorEyes** [mattgodbolt/jsbeeb#176]
JSBeeb seems to run at much less than 'normal' framerate when techniques are used that change the palette many times per line (e.g. 'racing the beam' raster effects).

As an example there is a sample SSD here:

https://bbc.godbolt.org/?autoboot&disc=https://vectoreyes.github.io/PaletteFunJSBeebReport.ssd

This initially displays a moving sine-wave pattern, and if you press space it displays a simple vertical-bars-test-card pattern. (If you press space again it may display the sine pattern again, but there is a known bug which means it may crash when re-entering the sine pattern).

These two effects are implemented by use of a stable raster technique, where the screen is set to MODE1, filled to only one colour (0xFF), and then code is executed at exact time-periods since the vertical retrace to change the palette multiple times per line.

I have tried this in both Edge and Chrome and it always runs slowly. B-Em seems to run it fine.

If I try setting the 'videoCyclesBatch' option to higher numbers (e.g. 10 or 50) then the effects run faster, but, unsurprisingly, look wrong.

To give an idea of what's happening behind the scenes, here is the code that's executed during each line of the 'vertical bars' effect. (So this is executed 256 times per frame):

.loop
    ldx #colFifteenToWhite
    stx &FE21
    sta &FE21
    stx &FE21
    ldx #colFifteenToGreen
    stx &FE21
    ldx #colFifteenToYellow
    nop
    stx &FE21
    ldx #colFifteenToMagenta
    nop
    stx &FE21
    ldx #colFifteenToRed
    nop
    stx &FE21
    ldx #colFifteenToCyan
    nop
    stx &FE21
    ldx #colFifteenToBlue
    nop
    stx &FE21
    nop
    ldx #colFifteenToWhite
    sta &FE21
    nop
    stx &FE21
    sta &FE21
    stx &FE21
    ldx #colFifteenToRed
    stx &FE21
    nop
    nop:nop:nop:nop:nop
    nop:nop:nop:nop:nop
    nop:nop:nop:nop:nop
    cmp &0
    dey
    bne loop

**Comment by mattgodbolt** [comment]
Nice! Thanks for this report. It's indeed true: I precache a lot of things in the rendering code on the assumption that the palette doesn't change often. If it does, that caching is more expensive than the work itself.

I'll need to re-investigate the options open to me.

**Comment by mattgodbolt** [comment]
A quick profile backs up this claim: the `updateFbTable` which is meant to be lazily evaluated only on the (assumed occasional) palette change is the culprit. Probably easy to back out the laziness and pay the (constant) cost each access. The offending check is: https://github.com/mattgodbolt/jsbeeb/blob/53e76588740a4a360bd3f5edc762abc57065ad1d/video.js#L400

**Comment by VectorEyes** [comment]
Thanks for replying to this issue so quickly! I had a look at the linked code and updateFbTable is looping 4096 times each time it's called so that's (worst case scenario, if changing the palette as rapidly as possible on every line) 20 * 256 * 4096 = approx. 20 million loop iterations per frame inside that function. Must confess I don't entirely understand what the FbTable is for. Some kind of acceleration structure to speed up copying bits of the Beeb's screen memory into the framebuffer? In any event, apologies for developing code that breaks your optimisations!

**Comment by mattgodbolt** [comment]
Right! So normally the palette isn't changing all that often. Every single pixel updated (usually) written needs to be mapped via two tables (one to map into the palette, and then from the palette table to the values I need to write to the JS screen). As that's done every other machine cycle, it made sense (at the time!) to trade off an expensive, rare, palette write against a cheaper single-lookup per pixel.

Please don't apologise for invalidating that guess :grinning: - this is the perfect excuse to get back in and look at the video code again. I'll take a look about backing out the "optimization" I made (again, more a trade-off).

**Comment by mattgodbolt** [comment]
Fixed in 9ef850e6e020ab3817e4ff199d15e0af751d3218 - not yet live.

**Comment by mattgodbolt** [comment]
Pushed live :) Tested and seems to be working :) If it doesn't look like it's working, try a "shift F5" page reload...caching is quite aggressive...
