### ISSUE TITLE
Timer differences between a real beeb

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#179]
See https://stardot.org.uk/forums/viewtopic.php?p=221420&sid=7389ea2ebfc6e794ccc85c224a0652fb#p221420 - there's a test SSD there and some results for a real beeb that differ from jsbeeb.

**Comment by murkle** [comment]
Also Snapper freezes at game start:
https://bbc.godbolt.org/?disc=sth%3AAcornsoft%2FSnapper-v2.zip&autoboot#

**Comment by mattgodbolt** [comment]
I'm gonna bust the Snapper thing to another issue --> #185

**Comment by scarybeasts** [comment]
Tests from my tests.ssd that still differ from a real beeb:

VIA.AC3
VIA.AC6
VIA.I1
VIA.I2
VIA.T21
VIA.T23

**Comment by scarybeasts** [comment]
[tests.ssd.zip](https://github.com/mattgodbolt/jsbeeb/files/3471167/tests.ssd.zip)

Attaching tests.ssd.zip for posterity.

I'll see how many of these are worth fixing and try and crank through them.

**Comment by scarybeasts** [comment]
I fixed everything except VIA.T23, which doesn't seem important. It's tricky for code to really rely on T2 values after toggling ACR 0x20 because results will vary depending on what is attached and generating pulses from external.

**Comment by mattgodbolt** [comment]
Thanks @scarybeasts ! I should work this into a test so we don't lose your fix too.
