### ISSUE TITLE
Screen clear on Master (shadow and normal flipping)

### ISSUE THREAD

**Issue by BigEd** [mattgodbolt/jsbeeb#181]
Planet Nubium development seemed to have a problem with screen clearing:
https://stardot.org.uk/forums/viewtopic.php?p=223299#p223299

> I have been testing the game on BeebEm and JSBeeb rather than a real machine.
> 
> The game uses video double buffering, flipping the video between main and shadow RAM every time it goes around the game loop, so clearing the screen has to clear both main and shadow RAM. This is done by 'PROCcls' line 920, and this line maybe failing on a real MASTER. Because the screen is not being cleared, there is text left on the screen which is repeatedly triggering the collision detection routine on level 1.
> 
> Line 920 moves main and shadow memory into the CPU's memory map, and then uses the BASIC 'CLS' command to clear the screen.
> 
> `920 DEFPROCcls:OSCLI("FX108,1"):CLS:OSCLI("FX108,0"):CLS:VDU19,0,0;0;19,1,0;0;19,2,0;0;19,3,0;0;:ENDPROC
> `

**Comment by mattgodbolt** [comment]
Thanks @BigEd ! Interesting one...I wonder what's going on ...
