### ISSUE TITLE
How to set read/write/execute breakpoints?

### ISSUE THREAD

**Issue by BigEd** [mattgodbolt/jsbeeb#183]
Presumably with some wizardry in the JavaScript console we could set up watchpoints or breakpoints and do some console.log?  Or is this capability already baked in??

From [a stardot thread](https://stardot.org.uk/forums/viewtopic.php?f=2&t=16568):
> Could some kind person help me out. In Jsbeeb would like to trap all writes to an area of memory ( say a page) and log these to either a window or a file . e.g. 
> ```
> Write address &3000 = &12
> Write address &3012 = &54
> Write address &3018 = &AB
> ```

**Comment by mattgodbolt** [comment]
It's not very easy to do but...

Bring up the JS console...and type:

```javascript
utils = require('utils');

processor.debugWrite.add((addr, b) => {
   if (addr >= 0x3000 && addr <= 0x3020) {
    console.log(`Write address &${utils.hexword(addr)} = &${utils.hexbyte(b)}`);
  }
});
```

To explain! `utils` provides a bunch of handy formatting things.

`processor` exposes a `debugRead`, and `debugWrite` interface where you can add handlers that are called with address (and byte for write).

`(addr, b) => { ... }` defines an inline function in javascript. The backtics allow you to write a string and then `${...}` takes the javascript result and puts it into the string at that point.

Hope that gets you started!

**Comment by mattgodbolt** [comment]
Other useful things:

`processor.pc` (and `a` and `x` and `y`) will show you which instruction caused the read or write and the registers there.

`processor.stop()` will breakpoint there.

If you need it too, there's a way to enable a rolling window of the last 256 PC, A, X and Y records, which can be very handy for debugging things!

**Comment by BigEd** [comment]
Great tips, thanks!

**Comment by BigEd** [comment]
(oops just noticed the helpful Debugger page on the wiki:
https://github.com/mattgodbolt/jsbeeb/wiki/Debugger
)

**Comment by mattgodbolt** [comment]
haha! I'd forgotten I'd written that else Id've linked in :)
