### ISSUE TITLE
Snapper freezes at startup

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#185]
https://bbc.godbolt.org/?disc=sth%3AAcornsoft%2FSnapper-v2.zip&autoboot#

```
10a5ad 60 fe.`. LDA $fe60
10a8cd 60 fe.`. CMP $fe60
10abf0 fb.. BEQ $10a8
```

Hangs here, with `A=ff`

(from #179)

**Comment by murkle** [comment]
It used to work, maybe bisecting would be useful: https://github.com/mattgodbolt/jsbeeb/issues/23

I had the same problem (symptom anyway!) with 6502Em for a long time - it was something subtle with VIA timers that only Snapper seems to use

**Comment by scarybeasts** [comment]
Relevant Stardot threads where we pinned down PB7 behavior on a real beeb:
https://stardot.org.uk/forums/viewtopic.php?f=4&t=16081
https://stardot.org.uk/forums/viewtopic.php?f=4&t=16263

Also attaching ssd with tests:
[tests.ssd.gz](https://github.com/mattgodbolt/jsbeeb/files/3437773/tests.ssd.gz)

With the PR, VIA.PB7 and VIA.PB2 now pass withe same results as a real BBC.

**Comment by mattgodbolt** [comment]
Confirmed all works on the site. Thanks @scarybeasts !
