### ISSUE TITLE
No sound in Safari browser on Mojave

### ISSUE THREAD

**Issue by lurkio** [mattgodbolt/jsbeeb#186]
As per the subject. JSBeeb produces no sound of any kind in Safari v12.1.1 on macOS Mojave v10.14.5.

Sound works on Mojave in Firefox though.

**Comment by mattgodbolt** [comment]
Thanks! Is there anything obvious in the Javascript console? Does clicking in the jsbeeb display "fix" it? Some browsers are starting to make sure the user interacts with the site before they allow it to make annoying noises. e.g. #184

**Comment by lurkio** [comment]
> Thanks! Is there anything obvious in the Javascript console? 

I'll have a look.

>Does clicking in the jsbeeb display "fix" it? Some browsers are starting to make sure the user interacts with the site before they allow it to make annoying noises. e.g. #184

Doesn't make any difference.  :-(

**Comment by lurkio** [comment]
Here's the JS console output in the Safari browser on macOS 10.14.6 Mojave:

>[Log] GL Canvas set up (main-e45ea3536538dc7654fe22627f2d1af01c926b08.js, line 11533)
>[Log] Loading OS from roms/os.rom (main-e45ea3536538dc7654fe22627f2d1af01c926b08.js, line 8260)
>[Log] 1.382716049382716 – 1.382716049382716 (main-e45ea3536538dc7654fe22627f2d1af01c926b08.js, line 12930)
>[Log] Loading ROM from roms/BASIC.ROM (main-e45ea3536538dc7654fe22627f2d1af01c926b08.js, line 8243)
>[Log] Loading ROM from roms/b/DFS-0.9.rom (main-e45ea3536538dc7654fe22627f2d1af01c926b08.js, line 8243)
>[Log] Using physical key layout (main-e45ea3536538dc7654fe22627f2d1af01c926b08.js, line 6556)
>[Error] The source list for Content Security Policy directive 'script-src' contains an invalid source: ''report-sample''. It will be ignored.
>[Error] The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.
>[Error] [Report Only] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (proxy.html, line 0)
>[Log] Google Drive: available (main-e45ea3536538dc7654fe22627f2d1af01c926b08.js, line 10128)
>[Log] Authorizing – true (main-e45ea3536538dc7654fe22627f2d1af01c926b08.js, line 10137)
>[Error] The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.
>[Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (iframe, line 0)
>[Log] Loading disc from discs/elite.ssd (main-e45ea3536538dc7654fe22627f2d1af01c926b08.js, line 8943)
>[Log] Google Drive: Need to auth (main-e45ea3536538dc7654fe22627f2d1af01c926b08.js, line 10149)
>[Log] authed = – false (main-e45ea3536538dc7654fe22627f2d1af01c926b08.js, line 12501)
>[Log] 1.382716049382716 – 1.382716049382716 (main-e45ea3536538dc7654fe22627f2d1af01c926b08.js, line 12930)

**Comment by mattgodbolt** [comment]
Thanks @lurkio . Sadly nothing obvious in there...I was hoping to see some web audio errors. But it seems like jsbeeb thinks it's making noises, but nothing's happening!

**Comment by lurkio** [comment]
> Thanks @lurkio . Sadly nothing obvious in there...I was hoping to see some web audio errors. But it seems like jsbeeb thinks it's making noises, but nothing's happening!

Anything else I can do to try and diagnose the problem? (I haven't a clue about JS, sadly.)

**Comment by lurkio** [comment]
@mattgodbolt Does this attached screenshot mean anything to you? The audioContext object seems to have a "state" property with a value of "suspended", which seems a bit ominous..? (Caveat: again, I don't really have a clue what I'm talking about.) 

<img width="1560" alt="Screenshot 2019-08-13 at 18 19 27" src="https://user-images.githubusercontent.com/26767174/62962664-43963500-bdf7-11e9-85ab-c9fe010490c8.png">

**Comment by richtw1** [comment]
@lurkio: Does typing `soundChip.jsAudioNode.context.resume()` on the console bring the sound back for you?

**Comment by lurkio** [comment]
> @lurkio: Does typing `soundChip.jsAudioNode.context.resume()` on the console bring the sound back for you?

No. There's still no sound.

**Comment by lurkio** [comment]
> > @lurkio: Does typing `soundChip.jsAudioNode.context.resume()` on the console bring the sound back for you?
> 
> No. There's still no sound.

See attached screenshot.

<img width="1235" alt="Screenshot 2019-08-14 at 16 33 37" src="https://user-images.githubusercontent.com/26767174/63034508-6a18a680-beb1-11e9-8672-61da5218074a.png">

**Comment by richtw1** [comment]
Your system has instanced `webkitAudioContext` instead of `AudioContext` (as per mine).  Maybe `webkitAudioContext` isn't working properly?  No idea about this API unfortunately.

**Comment by lurkio** [comment]
> Your system has instanced `webkitAudioContext` instead of `AudioContext` (as per mine). Maybe `webkitAudioContext` isn't working properly? No idea about this API unfortunately.

Through an amazing process of blindly typing things that I don't understand into the console, I managed to get sound working! I referred to this webpage:

https://www.mattmontag.com/web/unlock-web-audio-in-safari-for-ios-and-macos

I modified the code there and then pasted it into the console of a new running instance of JSBeeb:

`const audioCtx = soundChip.jsAudioNode.context;`

```
function unlockAudioContext(audioCtx) {
  if (audioCtx.state !== 'suspended') return;
  const b = document.body;
  const events = ['touchstart','touchend', 'mousedown','keydown'];
  events.forEach(e => b.addEventListener(e, unlock, false));
  function unlock() { audioCtx.resume().then(clean); }
  function clean() { events.forEach(e => b.removeEventListener(e, unlock)); }
}
```

`unlockAudioContext(audioCtx);
`

I was then able to type VDU 7 into the emulator and get a beep out of it for the first time ever!


<img width="1230" alt="1" src="https://user-images.githubusercontent.com/26767174/63038505-380b4280-beb9-11e9-86d5-7986a1f18cbb.png">

**Comment by richtw1** [comment]
Nice!  Sounds as if maybe adding a `resume()` into `keyDown()` might well fix your issue, as well as Chrome's, as per my suggestion in #184 .

**Comment by scarybeasts** [comment]
@mattgodbolt @richtw1 I don't have Safari so if one of you could check Safari (on Mojave I suppose) before approving, that would be great. It _should_ work because the standard here is pretty clear but Firefox was a bit finicky so you never know.

**Comment by lurkio** [comment]
@scarybeasts I just tested by deploying your branch on Netlify. It works in Safari on Mojave.

Orange no-sound warning banner comes up at first but goes away on click/keypress, and then sound is on! Many thanks!

**Comment by scarybeasts** [comment]
@lurkio Thanks for checking! That's awesome that it works. Out of curiosity, does Safari remember this "preference" at all?

Chrome has all sorts of rules: https://developers.google.com/web/updates/2018/11/web-audio-autoplay

Reading Chrome's rules, the good news is that a site structured like bbcmicro.co.uk might work without user interaction in the first place, since the user launches a game by interacting with the site, with jsbeeb hosted same origin.

**Comment by lurkio** [comment]
> Out of curiosity, does Safari remember this "preference" at all?

No, the warning banner comes up every time.

**Comment by scarybeasts** [comment]
@lurkio Interesting! Perhaps annoying if it persists.

On Chrome, the warning was coming up every time for me but then it stopped. I think what may have happened is that a new day rolled over, and Chrome now has metadata that I sort of "liked" (permitted and didn't closed sound for) the web origin yesterday so it should be permitted to autoplay going forward.

**Comment by lurkio** [comment]
@scarybeasts Just to mention that your fix seems to have enabled sound in Safari on iOS too, where there was previously no sound at all, just as on Mojave. 

So now JSBeeb can produce sound on iOS although there's obviously still no keyboard support.
