### ISSUE TITLE
reads of write-only registers

### ISSUE THREAD

**Issue by BigEd** [mattgodbolt/jsbeeb#189]
See this thread by scarybeasts:
https://stardot.org.uk/forums/viewtopic.php?f=4&t=17509&p=242598#p242598

On a real Beeb I get these results:
```
P.?&FC00
255
P.?&FD00
255
P.?&FEA0
182
P.?&FE21
190
?&FE00=15:P.?&FE00
0
?&FE02=15:P.?&FE02
0
?&FE00=0:P.?&FE01
0
?&FE02=0:P.?&FE03
0
```

On jsbeeb I get these results:
```
P.?&FC00
255
P.?&FD00
255
P.?&FEA0
254
P.?&FE21
254
?&FE00=15:P.?&FE00
15
?&FE02=15:P.?&FE02
15
?&FE00=0:P.?&FE01
63
?&FE02=0:P.?&FE03
63
```

**Comment by scarybeasts** [comment]
(Note that the referenced stardot thread continues with a note that the original results for FEA0 and FE21 stopped reproducing and starting giving 254s instead.)

**Comment by scarybeasts** [comment]
Now that we've ascertained correct behavior, a patch is pretty trivial, I'll crank out a PR.
