### ISSUE TITLE
Exile interrupt timing problem?

### ISSUE THREAD

**Issue by murkle** [mattgodbolt/jsbeeb#19]
The colour change point isn't quite right in Castle Quest's loading screen
http://bbc.godbolt.org/?disc=%7CMicropower%2FCastleQuest.zip&tape=%7CUltimate%2FSabreWulf_RUN_B.zip&autoboot

**Comment by mattgodbolt** [comment]
Leaving open as a placeholder for any potential exile water colour IRQ problem

**Comment by mattgodbolt** [comment]
Using some cheatery (`&2c2b - &2c2c = &ea`) I was able to scroll down to the water area, and observe a lovely single-pixel cyan line over a blue water area. Looks like it's working to me; happy to be proved otherwise though (as my cheat may not be valid).
