### ISSUE TITLE
Speech.dsd speech demo by D.A.W. and C.J.H. doesn't play

### ISSUE THREAD

**Issue by scarybeasts** [mattgodbolt/jsbeeb#193]
Breaking out from #167 because there's a separate issue.

http://bbcmicro.co.uk/gameimg/discs/1411/Speech.dsd
doesn't play the sound correctly in jsbeeb. It's because it repeatedly toggles on sound write enable without ever toggling it off, and the emulators want to see an on -> off transition before they send a byte of data over to the sound chip.

Looks like a real beeb is more permissive than that.

**Comment by scarybeasts** [comment]
Note that the playback on this one sounds pretty rough but I expect that is as expected. It uses the unusually large period of 8 for sample playback, which is a 15kHz wave, definitely in the audible range and probably prone to all sorts of harmonic distortion.

One interesting thing is that a real beeb has a low-pass filter? Maybe 8kHz? I might see if sound is generally improved by adding one.

**Comment by mattgodbolt** [comment]
A low-pass filter would be a cool addition: if you have access to a real beeb and any thoughts on "tuning" the two of them? Or are comfortable doing it by ear and memory - either works, really!
