### ISSUE TITLE
Dragonsoft Explorer hangs in the loader

### ISSUE THREAD

**Issue by scarybeasts** [mattgodbolt/jsbeeb#198]
https://bbc.godbolt.org/?autoboot&disc=https://dl.dropboxusercontent.com/s/2g55rr6qhv1vg80/PLAY_DISC.ssd&disc2=https://dl.dropboxusercontent.com/s/9zeyr1zotxw5v35/SAVE_DISC.ssd

Press "S" or "D" in the first selection menu, for single or double drives, it fails all the same.

**Comment by scarybeasts** [comment]
[explorer.zip](https://github.com/mattgodbolt/jsbeeb/files/3450123/explorer.zip)

Atttaching a zip for posterity in case the Dropbox versions disappear.

**Comment by lurkio** [comment]
A bit more info here:

https://stardot.org.uk/forums/viewtopic.php?f=1&t=598&p=188387#p188383

**Comment by scarybeasts** [comment]
Here we are. Uses OSWORD 0x7F to send raw i8271 disc command "read sector header ids" which wasn't wired up in the 8271 driver.

[ITRP] 20A9: LDA #$28       [A=FF X=00 Y=11 S=F1 F=CZ   1  ] 
[ITRP] 20AB: STA $02F0      [A=28 X=00 Y=11 S=F1 F=C    1  ] [addr=02F0 val=2F]
[ITRP] 20AE: LDA #$00       [A=28 X=00 Y=11 S=F1 F=C    1  ] 
[ITRP] 20B0: STA $02F6      [A=00 X=00 Y=11 S=F1 F=CZ   1  ] [addr=02F6 val=09]
[ITRP] 20B3: LDA #$0A       [A=00 X=00 Y=11 S=F1 F=CZ   1  ] 
[ITRP] 20B5: STA $02F7      [A=0A X=00 Y=11 S=F1 F=C    1  ] [addr=02F7 val=01]
[ITRP] 20B8: LDA #$02       [A=0A X=00 Y=11 S=F1 F=C    1  ] 
[ITRP] 20BA: STA $02F5      [A=02 X=00 Y=11 S=F1 F=C    1  ] [addr=02F5 val=00]
[ITRP] 20BD: LDA #$5B       [A=02 X=00 Y=11 S=F1 F=C    1  ] 
[ITRP] 20BF: STA $02F4      [A=5B X=00 Y=11 S=F1 F=C    1  ] [addr=02F4 val=53]
[ITRP] 20C2: LDA #$03       [A=5B X=00 Y=11 S=F1 F=C    1  ] 
[ITRP] 20C4: STA $02F3      [A=03 X=00 Y=11 S=F1 F=C    1  ] [addr=02F3 val=03]
[ITRP] 20C7: LDX #$EE       [A=03 X=00 Y=11 S=F1 F=C    1  ] 
[ITRP] 20C9: LDY #$02       [A=03 X=EE Y=11 S=F1 F=C    1 N] 
[ITRP] 20CB: LDA #$7F       [A=03 X=EE Y=02 S=F1 F=C    1  ] 
[ITRP] 20CD: JSR $FFF1      [A=7F X=EE Y=02 S=F1 F=C    1  ]

**Comment by richtw1** [comment]
It sounds like this image still has the protection intact, in which case it possibly wouldn't work with a standard .ssd disk image anyway.

I really need to find time to do a proper disk emulation, using a full FM/MFM bitmap internally (with the option to load more verbose disk formats).

**Comment by scarybeasts** [comment]
I didn't dig deep, but it looks like the loader code only cares that the first byte of the 0x1B response is 2 -- that's the track number that it asked for.

Game loads and appears to play fine.

Original stardot thread has a reference to the copy protection being removed (mainly checks for an installed ROM it sound like, but maybe disc stuff too):
https://stardot.org.uk/forums/viewtopic.php?f=1&t=598

Maybe the 0x1B call is a vestige of some old copy protection. Shrug :)
