### ISSUE TITLE
Dunjunz vs. sideways RAM configuration

### ISSUE THREAD

**Issue by scarybeasts** [mattgodbolt/jsbeeb#199]
There are various reports of Dunjunz not working. From quickly testing all the versions referenced in various threads, I think there are two issues:

- Disc060.dsd
Expects sideways RAM in banks 4 and 5, but jsbeeb's default beeb+swram model has chosen different banks. Error message is pretty clear.

- Dunjunz-swram.ssd
Expects sideways RAM in banks 1 and 2, but jsbeeb's default beeb+swram model has chosen different banks. Uninformative error message when it fails.

Other versions of Dunjunz, including the Master version, appear to load fine.

@mattgodbolt any particular reason you chose the sideways RAM banks as you did? Should we change them to accommodate the Dunjunz images? (Before anyone says "Exile", note that it will accept sideways RAM in any position.)

**Comment by scarybeasts** [comment]
Attaching zip of the two referenced versions for posterity.
[dunjunz.zip](https://github.com/mattgodbolt/jsbeeb/files/3450578/dunjunz.zip)

**Comment by lurkio** [comment]
Just linking to the Dunjunz comments here:

https://github.com/mattgodbolt/jsbeeb/issues/140#issuecomment-267735533

**Comment by mattgodbolt** [comment]
@scarybeasts Absolutely no science to the choices I made! As long as Exile still works, feel free to change them to anything!

**Comment by scarybeasts** [comment]
PR sent. It also makes Crazee Rider enhanced version work out of the box, which it currently does not.
