### ISSUE TITLE
check "Benchmark" games

### ISSUE THREAD

**Issue by murkle** [mattgodbolt/jsbeeb#21]
http://www.stardot.org.uk/forums/viewtopic.php?f=1&t=8164

**Comment by mattgodbolt** [comment]
* Pretty sure Exile's OK. 
* Nightshade/Lunar Jetman protection "works" - at least on the "Protection.ssd" copies I currently have. Will try and get casette images for these.
* Spy Hunter sounds just as awesome as I remember from 25-odd years ago.
* Zalaga works (yay). And is still as addictive as it was in the lunch rooms at school (with @richtw1 haha).

**Comment by mattgodbolt** [comment]
Any further thoughts on games to test here? I think we've covered most of the main ones listed on the thread, but I'm biased towards games I remember well.

**Comment by scarybeasts** [comment]
@mattgodbolt Can probably close this? jsbeeb runs almost everything these days.

**Comment by mattgodbolt** [comment]
Will do: thanks! Anyone finding games that don't run, please file a specific bug per game!

Thanks!
