### ISSUE TITLE
Menu at top doesn't let go of focus if you cancel the popup menu

### ISSUE THREAD

**Issue by richtw1** [mattgodbolt/jsbeeb#223]
Example repro:

- Click 'More'
- Click outside popup menu to make it disappear
- Up/down cursor keys now bring the menu back (as well as emulating the Beeb keypresses) because 'More' still has focus

**Comment by scarybeasts** [comment]
@richtw1 @mattgodbolt Oh that's interesting, I was grappling with a similar issue in my "paste" support so now I can re-use the same approach to fix this too. I'll see if there's a trivial change I can make on my "paste" branch and re-upload.

**Comment by scarybeasts** [comment]
BTW @richtw1, was this Menu -> Fullscreen -> Play Exile and scroll view using cursor keys? :)

**Comment by scarybeasts** [comment]
Fixed by https://github.com/mattgodbolt/jsbeeb/issues/164
