### ISSUE TITLE
Atic Atac STH tape image doesn't load

### ISSUE THREAD

**Issue by richtw1** [mattgodbolt/jsbeeb#241]
Loads the first custom block correctly, but fails on the second part (after the title screen has appeared) with a Data? error on block 1 (this is also a custom format I think).

**Comment by mattgodbolt** [comment]
Oh darn: what on earth made you re-check it? :) Does it work ok on other emulators (if it's quick to check?)

**Comment by scarybeasts** [comment]
b-em just loaded it ok, so sounds like there's something to fix here.

**Comment by scarybeasts** [comment]
Alright... Atic Atac not loading... we can't have that. I'll take a look.

**Comment by scarybeasts** [comment]
The other Ultimate STH tape images load ok (JetPac, Alien8, Knight Lore, Sabre Wulf).

**Comment by scarybeasts** [comment]
For posterity, other interesting tape files from STH include:

- The Hacker by Firebird.
Uses "defined data" UEF blocks which aren't super common and even seems to trigger a serial overrun condition at the end of the load.

- Chip Buster by Software Invasion.
Has a custom loading routine for the main file where the tape blocks count backwards from FF.
