### ISSUE TITLE
File saved to Google Drive image is missing after a refresh

### ISSUE THREAD

**Issue by ribbons** [mattgodbolt/jsbeeb#255]
My apologies if I'm being dumb and missing something obvious here but I'm saving a file to a disc on Google Drive and is isn't there if I reload jsbeeb:

Steps to reproduce:
https://bbc.godbolt.org/?disc=gd%3A[mydiscid]%2Fexport

```
*.
10PRINT "TEST"
SAVE "TEST"
*.
```
![image](https://user-images.githubusercontent.com/961548/64488946-b0a9b880-d245-11e9-8cd4-e86472999ede.png)

Browser console:
![image](https://user-images.githubusercontent.com/961548/64488978-0bdbab00-d246-11e9-90ce-db1503cb7e3c.png)

After refreshing the page:
![image](https://user-images.githubusercontent.com/961548/64488990-362d6880-d246-11e9-9f85-9febcb048b74.png)

Browser console:
![image](https://user-images.githubusercontent.com/961548/64488995-4d6c5600-d246-11e9-977b-e78da87312de.png)

The disc image shows as updated in Google Drive with the timestamp of when it should have saved, but the stored disc image is empty:

[export.zip](https://github.com/mattgodbolt/jsbeeb/files/3587647/export.zip)

**Comment by mattgodbolt** [comment]
Zoiks! thanks. There4's a short delay before things get saved (in theory) to prevent tons of writes to Google Drive...if oyu give it "a while" (like 5 seconds) does it save?

Will take a look in the next few days: Thanks!

**Comment by mattgodbolt** [comment]
thanks for posting the JS console...just checked the code and we ought to have seen "Saved ok" at some point....debounced by 200ms, so...I'm guessing something is broken!

**Comment by scarybeasts** [comment]
Oh, just saw this bug.

Terribly sorry about that I think I must have broken it recently? Can we blame JavaScript scoping rules? :)

Anyway this is landed and should fix it: https://github.com/mattgodbolt/jsbeeb/commit/6cdeed8120a6d438a2055847157e3ab5249b669b

Let me know if it doesn't!

**Comment by ribbons** [comment]
Thanks both!  Tested and working successfully now :+1:.

No need at all to apologise after your good work recently @scarybeasts :smiley:.
