### ISSUE TITLE
Caveman Capers tape image doesn't load

### ISSUE THREAD

**Issue by scarybeasts** [mattgodbolt/jsbeeb#262]
https://www.stairwaytohell.com/bbc/archive/tapeimages/Icon/CavemanCapers_B.hq.zip

The UEF loads on BeebEm, and also on a real beeb via uef2wave.py.

Caveman Capers is listed here as an interesting title for copy protection: http://beebwiki.mdfs.net/List_of_copy_protected_software_titles_on_cassette

**Comment by scarybeasts** [comment]
This one is going to be nasty.

Notes part 1:

Loader is at &1100
- &1100: loads big file CAPERS2 via OSCLI L.CAPERS2
- &1107: OSCLI L.TUNE
- &110e: OSBYTE 205, X=&40: select RS423
- &1117: OSBTYE 7 / 8, X=3, receive / transmit 300 baud
- &1129: OSBYTE 156 x 2, update ACIA control register
- &113b: OSBYTE 137, X=1, cassette motor on
- &1144: OSBYTE 2, X=2, RS423 is input stream
- &114d, OSBYTE 156, update ACIA control register
- &11bf, manually write "Searching" to the screen (cheeky!)

**Comment by scarybeasts** [comment]
- &11cc: OSRDCH twice until &2a &2a. (Tape stream appears to hit after &2a &00 &2a &2a)
- &11da: manually write "Loading" to the screen
- &11e7: read 47 bytes into &700 using OSRDCH. Checksum maintained in &70, which passes.
- &1159, OSBYTE 2, X=0, keyboard is input stream
- &1162: OSBYTE 156, update ACIA control register
- &116b: OSBYTE 137, X=0, cassette motor off
- &1174: OSBYTE 13, X=4, disable start of vsync event
- &117b: manual writes to the screen, effect is to change to MODE 7
- &119e: OSCLI, R. START

**Comment by scarybeasts** [comment]
Everything appears to be in order except that the final *R. START doesn't quite work properly because some state somewhere must have been left screwed up. The "copy protection" has run and decided its happy with the non-standard tape bytes it read.

**Comment by richtw1** [comment]
What's the vsync event doing?  Is it possible that there's a subtle timing issue here?  e.g. if it's expecting to get a vsync N times while it loads the special stream?

**Comment by richtw1** [comment]
By the way, this loading code seems almost identical to AUG P.314.  Main difference seems to be *FX 2,2 instead of *FX 2,1 (meaning that keyboard is selected?), and lack of DCD detection?
