### ISSUE TITLE
Shift doesn't do uppercase when Caps Lock off

### ISSUE THREAD

**Issue by lurkio** [mattgodbolt/jsbeeb#297]
In Firefox and Chrome, both on Mac, if you turn Caps Lock off and then try to produce a capital letter using Shift+letter-key, nothing happens!

**Comment by lurkio** [comment]
Oh, hang on -- it works, but only if I switch to a different brower-tab and then back to the JSBeeb tab!

**Comment by mattgodbolt** [comment]
Super odd! Is this still happening? I'm going to close as "hopefully fixed by a random update/browser fix" but if not please reopen!

**Comment by yqxq** [comment]
Still happening. We also want a way to select Caps-lock (click on the LED light for example), as 99% of Mac users permanently disables CAPS LOCK, so to type lowercase in JSBEEB you need to change system preferences.

**Comment by mattgodbolt** [comment]
Thanks. I now have a Mac so I can at least try and fix this.

**Comment by mattgodbolt** [comment]
Looks like this is related to #29 where Mac browsers consider caps lock to be "held down" when caps lock is on.

**Comment by mattgodbolt** [comment]
It looks like this is not possible in general to fix: capslock on Mac is just "broken" : 
> All in all the Caps-lock key does not work properly and this is a serious issue.
from [here](https://bugzilla.mozilla.org/show_bug.cgi?id=712535#c6)

**Comment by mattgodbolt** [comment]
though: https://stackoverflow.com/questions/39016292/keydown-event-is-not-fired-for-capslock-in-mac looks promising

**Comment by mattgodbolt** [comment]
No, that doesn't work. It'll tell us if the _Mac_ caps lock is on or off, but still I only get a "press" when capslock is turned on, and a "release" when capslock is turned off; not when the key itself is released.

A workaround would be to fake a "tap" of capslock on both a keydown and a keyup on macs; which _might_ paper over it enough to be usable.
