### ISSUE TITLE
Support protected disc image formats

### ISSUE THREAD

**Issue by ghost** [mattgodbolt/jsbeeb#30]
Would be good to support a protected disc image format (for the purpose of perfect preservation of disc titles).  .fdi is a very bloaty but bit-perfect format which can represent any disc format (FM/MFM etc).  .fsd is a format invented by Bill Carr, DFS only, based on .ssd, but with extra sector/track ID information interleaved.  Info on fsd here: http://www.stardot.org.uk/forums/viewtopic.php?p=63142

**Comment by mattgodbolt** [comment]
We now support HFE discs, and things like Exile and other protected discs load just fine (yay). Hope that works for you!
