### ISSUE TITLE
Kernel for Jupyter/Iodine?

### ISSUE THREAD

**Issue by rog77** [mattgodbolt/jsbeeb#300]
Sorry if this is in the wrong place, but I wonder how difficult it would be to adapt this project to work with an Iodine notebook as a runtime / kernel? Thanks !

**Comment by mattgodbolt** [comment]
Hi! Interesting question: probably not _too_ bad. There's already a twitter bot that "types" in the code and we could use similar tricks (we use it for testing too, and can capture BASIC output). graphics might be tough.

**Comment by rog77** [comment]
https://mobile.twitter.com/bbcmicrobot was what inspired me to ask the question, if people are into sharing bits of BBC Basic code, maybe the notebooks would be used?

**Comment by mattgodbolt** [comment]
Not quite the same but [Owlet](https://bbcmic.ro/) might be part of what you want. See also [its github page](https://github.com/mattgodbolt/owlet-editor)

**Comment by rog77** [comment]
Thanks :-)
