### ISSUE TITLE
Hell-Hole game freezes 

### ISSUE THREAD

**Issue by lurkio** [mattgodbolt/jsbeeb#302]
Hi. We've had a bug report from a user of bbcmicro.co.uk about the game Hell-Hole: it freezes in JSBeeb when you go down to the bottom of the screen on the first level and try to collect the diamonds:

http://bbcmicro.co.uk/game.php?id=728

The bug manifests in the version of JSBeeb installed on bbcmicro.co.uk, which is now the same as the latest version of JSBeeb in this Github repo and also (presumably) the same as the version installed on bbc.godbolt.org, where the bug _also_ manifests.

The bug *doesn't* manifest in Mac BeebEm: i.e. the game continues to play normally even after you've collected the diamonds. (I haven't tried Win BeebEm or any other emulators.)

**Comment by mattgodbolt** [comment]
Confirmed: https://bbc.godbolt.org/?&disc1=sth%3AAlligata%2FHellHole-electron.zip# freezes at the bottom. Seems stuck in a routine around `$1d57`ish 
![Screenshot from 2020-05-06 12-32-45](https://user-images.githubusercontent.com/633973/81209145-bd79da00-8f95-11ea-9814-7bc863b4a147.png)

**Comment by lurkio** [comment]
Turns out the game runs if the active FS is DFS1.2 or tape:

https://stardot.org.uk/forums/viewtopic.php?f=51&t=17942&p=268150#p268147
