### ISSUE TITLE
Corrupted text display after switching from graphics mode

### ISSUE THREAD

**Issue by uecasm** [mattgodbolt/jsbeeb#304]
I'm not sure which version of JsBeeb they're using (perhaps it's outdated), but I recently noticed that immediately on startup of:

    http://bbcmicro.co.uk//jsbeeb/play.php?autoboot&disc=http://bbcmicro.co.uk//gameimg/discs/2135/Disc999-IslandOfSecrets.ssd&noseek

It displays a glitchy border, the correct startup title graphic, and then switches back to text mode, leaving the glitchy border and corrupted trails of the title graphic in the background of the text area.

At https://bbc.godbolt.org/ that same disk image seems a little different; it usually doesn't show the corrupted border at first, but still displays the corrupted background.  And if you press shift-F12 a second time, then it corrupts the border as well.

It doesn't seem entirely deterministic, though -- the actual corrupted image changes a little each time, and every once in a while it will successfully clear the background (if not the border).

**Comment by uecasm** [comment]
If it helps, you can see the content of the disk file [here](http://bbcmicro.co.uk/explore.php?id=2135) -- click on Display next to `IOSLOAD`, which is the code that displays the startup title.

If I'm reading that correctly, it's drawing the title in `MODE 1` and then switching to `MODE 6` for the rest of the game, but something about that isn't clearing the screen properly.

**Comment by uecasm** [comment]
Hmm.  Can't reproduce this on Firefox, only in Chrome.

**Comment by mattgodbolt** [comment]
What version of Chrome are you using? @richtw1 recently had this and when he upgraded from Chrome 81 to Chrome 83 it went away.

**Comment by uecasm** [comment]
Ah, maybe that's it then.  I'm also on 81.  My apologies for the noise.
