### ISSUE TITLE
Fortress from SAM5 his non-TT on loading screen and corrruption left during gameplay

### ISSUE THREAD

**Issue by richard-broadhurst** [mattgodbolt/jsbeeb#309]
Fortress from SAM5 his non-TT on loading screen and corrruption left during gameplay
[DiscA06-FortressSAM5.zip](https://github.com/mattgodbolt/jsbeeb/files/5365988/DiscA06-FortressSAM5.zip)

![image](https://user-images.githubusercontent.com/22466543/95763100-83c8a000-0ca6-11eb-870b-0dfc6d1ce4d1.png)

**Comment by richard-broadhurst** [comment]
![image](https://user-images.githubusercontent.com/22466543/95763434-ede14500-0ca6-11eb-87d2-ff3c757ed5df.png)

**Comment by mattgodbolt** [comment]
Was unable to reproduce in Chrome 88 on Linux; can you let me know which browser you're using? I know we've seen these kinds of corruptions come and go with Firefox versions...

**Comment by mattgodbolt** [comment]
@richtw1 suggests - quite rightly - this is probably a texture reuse thing where jsbeeb is relying on content being the same (or blank?) but really we're in "don't do that" territory. Different drivers might do different things. ie this is definitely a jsbeeb bug!

**Comment by mattgodbolt** [comment]
Going to close -- if you ever see this again please post back/reopen/open a new issue. Lots of things could be the culprit and we've made a ton of changes since this was filed.
