### ISSUE TITLE
Teletext: Change to text mode should reset the held character

### ISSUE THREAD

**Issue by hoglet67** [mattgodbolt/jsbeeb#316]
Here's another sequence that doesn't quite work correctly:

VDU &91,&61,&9E,&92,&93,&94,&81,&91,&91,10,13

The &81 should reset the held character to a space, and to that as "set after". On JSBeeb the held character remains.

![Screenshot from 2021-02-06 10-51-36](https://user-images.githubusercontent.com/1951463/107116166-5d3bff80-6869-11eb-8735-cfafd6360ee7.png)

Here's the read hardware:
![capture3](https://user-images.githubusercontent.com/1951463/107116220-96746f80-6869-11eb-8a40-29af0fd5e2d7.png)

**Comment by mattgodbolt** [comment]
With the new teletext tests in place, we can look at fixing this (and locking in the good behaviour to boot!)
