### ISSUE TITLE
ROMs can't write to their own SWRAM bank?

### ISSUE THREAD

**Issue by lurkio** [mattgodbolt/jsbeeb#317]
The MRM-E00 DFS uses its own SWRAM bank as workspace and leaves PAGE at &E00 in a standard Model B. 

But in JSBeeb PAGE is set at &1700, presumably because the MRM-E00 DFS ROM isn't able to write to its own SWRAM bank for some reason and has to claim workspace from User RAM..?:

https://bbc.godbolt.org/?autoboot&disc=https://dl.dropboxusercontent.com/s/gfdgvtj0qmi7ifr/E00test.ssd

**Comment by mattgodbolt** [comment]
Hi... jsbeeb doesn't do anything special or clever. I don't know what MRM does, or why it doesn't interact with jsbeeb in the same way as a real beeb.  What is MRM?

> write to its own SWRAM bank

Which SWRAM bank? jsbeeb makes up a sort of nasty hack for sideways ram to make Exile run in enhanced mode, but I don't know if there's something I'm not doing right.

**Comment by lurkio** [comment]
I think MRM is just the name of the company that released the DFS back in the day.

> > write to its own SWRAM bank

> Which SWRAM bank?

Whichever SWRAM bank the MRM-E00 DFS happens to be loaded into. 

It all works in BeebEm, once you've made the SWRAM bank writable via one of the menus in BeebEm.

**Comment by mattgodbolt** [comment]
So - this is a ROM that expects to be in RAM? A DFS that needs to be in SWRAM and then uses RAM in its bank instead of bumping `PAGE` ?

All jsbeeb's swram banks are RAM and are writeable (else you wouldn't be able to load into it.

What's the output of your test disc on BeebEm?

**Comment by mattgodbolt** [comment]
![Screenshot from 2021-03-12 13-58-52](https://user-images.githubusercontent.com/633973/110992112-185d2a00-833b-11eb-9506-a8b1144b535c.png)
jsbeeb output ^

**Comment by lurkio** [comment]
You need to go to the Hardware menu in BeebEm and make the SWRAM slot writable.

**Comment by mattgodbolt** [comment]
I don't have BeebEm; can you please post what you're seeing in BeebEm?

**Comment by mattgodbolt** [comment]
mainly I want to see if it loads into ROM 01 and ROM 00 as it does on jsbeeb

**Comment by lurkio** [comment]
<img width="640" alt="Screenshot 2021-03-12 at 20 03 46" src="https://user-images.githubusercontent.com/26767174/110992656-1cef0600-836e-11eb-9801-f3f6816476c2.png">

**Comment by mattgodbolt** [comment]
Got it; thanks. I'm stumped I'm afraid! I don't know what I might not be emulating to cause it to use PAGE memory.

You have a different DFS in ROM 14 too, so I wonder if there's an interaction on jsbeeb of it having two DFS 0.90s?

**Comment by lurkio** [comment]
That could be it!

<img width="640" alt="Screenshot 2021-03-12 at 20 08 49" src="https://user-images.githubusercontent.com/26767174/110993144-d057fa80-836e-11eb-8ed0-33a0e98dd690.png">

**Comment by lurkio** [comment]
Yep! Thanks!:

https://bbc.godbolt.org/?autoboot&disc=https://dl.dropboxusercontent.com/s/gfdgvtj0qmi7ifr/E00test.ssd&model=b-dfs1.2

**Comment by mattgodbolt** [comment]
Fantastic! Glad you worked it out: I must admit to being somewhat clueless in anything other than lowish level hardware stuff, and playing Exile :grinning:

**Comment by Pernod70** [comment]
To add some info on the MRM 0E00 DFS, it's an 8K ROM that came on a carrier board with 2K RAM. The RAM was mapped into the upper 8K of the 16K bank. So the lower 8K is ROM, and the upper 8K is RAM (not fully decoded so is mirrored). It should work in sideways RAM but that is not how it was intended to be used.
