### ISSUE TITLE
Support an audio filter of some kind

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#33]

**Comment by scarybeasts** [comment]
@mattgodbolt this is pretty trivial with HTML5 if you're interested. If you want to screw around with a low pass filter, for example, just apply below simple patch.

And then when some audio is playing (Enjoy The Silence perhaps :) you can tweak values to see playback effect, e.g.

soundChip.filterNode.frequency.value = 2000
soundChip.filterNode.Q.value = 20

(I don't know if it responds to other parameters.)

I'm not much of an audio connoisseur so I'll leave it you to play with and decide if it is warranted to add one. Also, my high quality headphones are missing so good testing is hard on these awful laptop speakers.
Note that someone experienced in the hardware side of the beeb states it has an 8kHz low pass filter:
https://stardot.org.uk/forums/viewtopic.php?f=4&t=17537#p243399


diff --git a/main.js b/main.js
index ed50c78..82de2fd 100644
--- a/main.js
+++ b/main.js
@@ -191,7 +191,12 @@ require(['jquery', 'underscore', 'utils', 'video', 'soundchip', 'ddnoise', 'debu
                 var chan = outBuffer.getChannelData(0);
                 soundChip.render(chan, 0, chan.length);
             };
-            soundChip.jsAudioNode.connect(audioContext.destination);
+            soundChip.filterNode = audioContext.createBiquadFilter();
+            soundChip.filterNode.type = 'lowpass';
+            soundChip.filterNode.frequency.value = 8000;
+//            soundChip.jsAudioNode.connect(audioContext.destination);
+            soundChip.jsAudioNode.connect(soundChip.filterNode);
+            soundChip.filterNode.connect(audioContext.destination);
             ddNoise = new DdNoise.DdNoise(audioContext);
         } else {
             soundChip = new SoundChip.FakeSoundChip();

**Comment by scarybeasts** [comment]
Hmm the patch got mangled trying to attach.

[filter.diff.txt](https://github.com/mattgodbolt/jsbeeb/files/3446135/filter.diff.txt)

**Comment by mattgodbolt** [comment]
Nice: I replied in the (now closed) issue. I'll give this a go when I have some time (and/or will ask some other pals to take a look too!)

**Comment by richtw1** [comment]
Beeb service manual says:

> The audio output of the speech system device is filtered by an operational amplifier circuit with a cut-off frequency of 7 kHz. This signal is then added to an amplified and level shifted signal from the sound generator by a virtual earth amplifier to which is also added an extra analogue input from the 1 MHz extension bus. This summated audio signal is then finally filtered by an **8 kHz low pass filter**. All of these operations are done by a quad operational amplifier (IC17). IC19 provides audio power amplification to drive a speaker from PL15. A low level audio output is provided from PL16 for feeding the auxiliary input of an external power amplifier.

http://wiki.itmuseum.in.ua/images/8/8b/Acorn_BBCSMOct85_Sec1.pdf Section 3.8

**Comment by inversephase** [comment]
any possibility to make this filter configurable? the ability to toggle it on/off and select where the cutoff is on the user end would be helpful for some of us sound nerds =]

**Comment by scarybeasts** [comment]
I found my decent headphones so I can carry this over the finish line and make sure there are parameters.

**Comment by scarybeasts** [comment]
Ok, Q value of 5 seems to give a clean sound so used that as default, along with 7khz.

The music in the Master version of Stryker's Run is a good test, it uses big bold square waves. For experimentation, I recommend flipping values around "live" to hear to the difference. This is done via the console as per my Jul 30 comment above.

**Comment by mattgodbolt** [comment]
Sounds great! If it can be tweaked (by a URL param) I'd be happy to merge as it is and let folks play with it a bit (looking at you @inversephase and the stardot people...)

@scarybeasts do you have access to a real beeb to do a side-by-side? Tough one I know!

**Comment by scarybeasts** [comment]
Sadly I don't have a real beeb :(
