### ISSUE TITLE
Potential issue concerning use of HIMEM?

### ISSUE THREAD

**Issue by sassquad** [mattgodbolt/jsbeeb#331]
Came across this issue, when playing my game Androidz Redux.

When the game is over, the verdict program is supposed to load. However, what instead happens is this:

<img width="349" alt="Screenshot 2021-11-01 at 23 39 27" src="https://user-images.githubusercontent.com/2427885/139756241-b95d6fc1-3d9e-4c9b-a5b4-1985a6f616b5.png">

Clearly, the program attempts to load part 3, but it freezes.

The line in question is within DROID2, as follows:

`14$&900=STR$(s):MODE7:HIMEM=&2763:PAGE=&1900:OSCLI"DISC":CHAIN"DROID3":END`

The attached [AndroidzReduxBroke.zip file](https://github.com/mattgodbolt/jsbeeb/files/7456701/AndroidzReduxBroke.zip) contains an edition of the game with lives set to zero, so you can see the issue for yourself. In the end, I had to remove the `HIMEM=&2763` part in order for the game to work. I found that the b2 emulator on Mac, and Beebem on Windows 10 could run the code fine unaltered. 

A thought occurred as to whether PAGE should be set first, before setting HIMEM, but the fact that jsbeeb seemed to jibber unlike the others, made me think this perhaps deserves a closer look?

**Comment by regregex** [comment]
Confirmed but only under DFS 0.9. Works for me with DFS 1.2 installed.

**Comment by regregex** [comment]
Hangup reproduced on a model B with DFS 0.9.  True to hardware, unfortunately.

**Comment by sassquad** [comment]
> Hangup reproduced on a model B with DFS 0.9. True to hardware, unfortunately.

Apologies for coming to this late. I'll probably have to close this, given that it's reproducible on hardware!
