### ISSUE TITLE
Debug screen on by default

### ISSUE THREAD

**Issue by mfraser** [mattgodbolt/jsbeeb#339]
As soon as I load my local copy of jsbeeb, the debugger is loaded and there doesn't seem to be any way of getting rid of it. I can step through with "g", but as soon as I press "break" it appears again.

**Comment by mattgodbolt** [comment]
Can you check the Javascript debugger output? The jsbeeb debugger also pops up if there'a an uncaught JavaScript exception: I wonder if some error is being thrown.

**Comment by mfraser** [comment]
Uncaught TypeError: navigator.getGamepads is not a function
    getGamepads http://192.168.2.109/jsbeeb/main.js:578
    getGamepads http://192.168.2.109/jsbeeb/via.js:575
    getJoysticks http://192.168.2.109/jsbeeb/via.js:583
    read http://192.168.2.109/jsbeeb/via.js:273
    readDevice http://192.168.2.109/jsbeeb/6502.js:643
    readmem http://192.168.2.109/jsbeeb/6502.js:701
    anonymous http://192.168.2.109/jsbeeb/6502.opcodes.js line 1153 > Function:11
    exec http://192.168.2.109/jsbeeb/6502.opcodes.js:1156
    executeInternalFast http://192.168.2.109/jsbeeb/6502.js:1069
    execute http://192.168.2.109/jsbeeb/6502.js:1040
    draw http://192.168.2.109/jsbeeb/main.js:1385
main.js:578:34

**Comment by mattgodbolt** [comment]
It seems the fix for this issue was put in place a while back -- the lines numbers your error reports don't match. Can you check you have the latest code?

```js
    getGamepads: function () {
        // Gamepads are only available in secure contexts. If e.g. loading from http:// urls they aren't there.
        return navigator.getGamepads ? navigator.getGamepads() : [];
    }
```

should be the code it's trying to run, which checks carefully if the `gamepads` is available before trying to use them.

**Comment by mfraser** [comment]
Yes, it is up-to-date as I cloned it from github just now.
Oddly a version I downloaded in November last year works.

**Comment by mattgodbolt** [comment]
I wonder: we changed the default branch a ways back -- try `git checkout main`

**Comment by mattgodbolt** [comment]
(I switched the default branch name to `main` to fit the default GH now has and to serve my poor old muscle memory better)

**Comment by mattgodbolt** [comment]
What URL are you hitting specifically to see this? If it's not `localhost` then maybe it's a new security feature in some browsers that hides some of the new features if not served either on https OR localhost. And also, did you ensure you're on `main`? Gonna close in the hope that either of these things fixes it but let me know if you still have issues!
