### ISSUE TITLE
Beeb screen too small in Turbo model

### ISSUE THREAD

**Issue by BigEd** [mattgodbolt/jsbeeb#340]
I'm seeing the cubmonitor and bbc screen at size of approx 224px wide, regardless of window and zoom setting, for the Turbo model but not for the B or Master models.

Looks like 3 elements have specified height and width: cub-monitor, cub-monitor-pic, and screen.

**Comment by mattgodbolt** [comment]
We're _hoping_ it's fixed now @BigEd - going to cross our fingers and close this; and then please reopen if you see it again on the main bbc.godbolt.org site!
