### ISSUE TITLE
Parity in tapes is ignored.

### ISSUE THREAD

**Issue by CommanderCoder** [mattgodbolt/jsbeeb#370]
Comparing the byte in the `UInt8Array` with the string won't work here:
https://github.com/mattgodbolt/jsbeeb/blob/09ebe87b17d2532146e40d77e37f498611e906d2/tapes.js#L105

I couldn't find a BBC tape that falls foul of this error but when I was trying out files for the Acorn Atom I could only get this to work by converting to a string character first using `fromCharCode`.
https://github.com/CommanderCoder/JSATOM/blob/fb0a1147bf678a569c6e55338a85be5f81d8aaa7/tapes.js#L171

**Comment by mattgodbolt** [comment]
Oh yikes, nice spot!
