### ISSUE TITLE
Some instructions fail my timing test suite

### ISSUE THREAD

**Issue by dp111** [mattgodbolt/jsbeeb#371]
I've created a 6502/ 65C12 instruction timing test suite [https://github.com/dp111/6502Timing](https://github.com/dp111/6502Timing) thread discussing the test suite on [stardot](https://stardot.org.uk/forums/viewtopic.php?f=55&t=25298). Main errors appear to be  in Master emulator with clock stretching ( 65C12timing1M.ssd). I did have a quick look at doing a pull request , but your code is too clever for me :)

**Comment by dp111** [comment]
6502timing1M.ssd on a bbc B with jsbeeb gives the following instruction timing errors which all look like page cross errors during 1MHz clock stretching

![image](https://user-images.githubusercontent.com/19616418/187023206-010fd9af-6f2c-4a08-a8bd-d42170916746.png)

**Comment by dp111** [comment]
On a jsbeeb master with 65C12timing1M.ssd again all the errors look like they are to do with page crossing and 1MHz clock stretching 

![image](https://user-images.githubusercontent.com/19616418/187023327-a4c322d3-713d-486a-95a7-396c3c9d128f.png)
![image](https://user-images.githubusercontent.com/19616418/187023341-dccd715c-5e3b-4087-8bf6-997055431e21.png)

**Comment by mattgodbolt** [comment]
oh amazing! I can make a test suite out of this (with your permission, if I can embed your SSD in the repository).

The code is a bit too clever for its own good, it tries to "compile" instructions. I bet it'll be a fairly easy fix once I remember how that stuff works too :D

**Comment by mattgodbolt** [comment]
Wow, I'm shocked there's any regular 6502 timing issues left though! wowser :)  I figured all the Kevin Edwards protection system stuff would have flushed them out. Awesome!

**Comment by mattgodbolt** [comment]
Actually can probably submodule this in so that everything Just Works Nicely™

**Comment by dp111** [comment]
version 0.22 at the end of the tests stores the number of failures at &FCD0
so emulators can trap this to detect pass or fail.

**Comment by mattgodbolt** [comment]
Actually in terms of convenience (not having to get a portable version of beebasm etc etc), would it be OK to build and ship disc images of your timing tests alongside jsbeeb?

**Comment by dp111** [comment]
No problem.

**Comment by mattgodbolt** [comment]
D'oh I should have checked...you already have the ssds in your repo. I'm sorry...nothing to see here please move along
