### ISSUE TITLE
gdrive support is broken

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#377]
```
Access blocked: jsbeeb’s request is invalid

You can’t sign in because jsbeeb sent an invalid request. You can try
again later, or contact the developer about this issue. Learn more
about this error
If you are a developer of jsbeeb, see error details.
Error 400: redirect_uri_mismatch
```

**Comment by stuaxo** [comment]
Confirmed on https://bbcmicro.co.uk/jsbeeb/

I can see there is a part of the message about redirects failing, has jsbeeb moved since this was created ?

![image](https://user-images.githubusercontent.com/179677/196829113-bbfec020-d625-4418-9cf2-c589ebeb8b3a.png)

**Comment by mattgodbolt** [comment]
jsbeeb has always been at https://bbc.godbolt.org/ but it is open source, so folks can host it anywhere, as do the wonderful people at bbcmicro.co.uk

I'll add their address to the list of "ok" places in my gdrive code!

**Comment by mattgodbolt** [comment]
...if I can find out where to do that in google's console...

**Comment by mattgodbolt** [comment]
Found it I think!

**Comment by mattgodbolt** [comment]
Says it'll take 5m to an hour to take effect. Will check back

**Comment by mattgodbolt** [comment]
Oh! It's working for me now already! yay. Let me know how it goes: closing this for now.
