### ISSUE TITLE
*fx200,3 not working

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#378]
To repro:
1. ?&3000=12
2. *fx200,3
3. call!-4
4. P.?&3000

should be cleared but isn't! Super odd

**Comment by tom-seddon** [comment]
Could it be the clear routine skipping the first byte of every page? - https://tobylobster.github.io/mos/mos/S-s10.html#SP4

**Comment by mattgodbolt** [comment]
zomg you might be right there! One thing the reporter (over email) said was the "32K" didn't pop up, which I've noticed too. so I wonder if there's something else going on too

**Comment by tom-seddon** [comment]
I'm 99% sure you have to take extra measures to get the 32K to appear when doing `CALL!-4`, which is otherwise equivalent to just pressing BREAK on its own.

**Comment by mattgodbolt** [comment]
:+1: thanks Tom

**Comment by dy-tray** [comment]
Yeah, the System VIA is implicated here, IIRC. It sets some state when it's powered up which the MOS checks and later clears, which is how it knows whether it's a cold (power-on) reset.

**Comment by codeaholics** [comment]
Yeah, the System VIA is implicated here, IIRC. It sets some state when it's powered up which the MOS checks and later clears, which is how it knows whether it's a cold (power-on) reset.
