### ISSUE TITLE
Emulate BBC Master's RTC?

### ISSUE THREAD

**Issue by lurkio** [mattgodbolt/jsbeeb#388]
Like earlier versions of B-em, JSBeeb _doesn't_ faithfully emulate the setting of the time on the real-time clock in the BBC Master (details linked below). _Should_ it?

[https://stardot.org.uk/forums/viewtopic.php?p=384117#p384117](https://stardot.org.uk/forums/viewtopic.php?p=384117#p384117)

**Comment by mattgodbolt** [comment]
The current jsbeeb uses the browser's time:

![image](https://user-images.githubusercontent.com/633973/217950358-a50db623-fa9b-4f99-a9d4-504b2e545b90.png)

Is that not what's expected? Perhaps we need to detect if someone tries to configure the time and "back out" the adjustment required, so the clock can be reconfigured?

**Comment by mattgodbolt** [comment]
Seems like catching writes and rebasing the clock is probably something we should do.

**Comment by mattgodbolt** [comment]
It's not quite as simple as I'd hoped (what is?). This partial solution supports setting the clock but doesn't support setting a "bad" day. The Beeb let you set the wrong day and would carry on regardless, but without a larger change to faithfully emulate the once-a-second counter of the CMOS clock and its oddities (and leap year handling etc) I'm using the JS functions, that don't let you lie that Feb 19th was a Wednesday etc :)

**Comment by mattgodbolt** [comment]
Closing as "good enough" for now :)
