### ISSUE TITLE
Keyboard layout - essential keys missing

### ISSUE THREAD

**Issue by DATHKA** [mattgodbolt/jsbeeb#396]
There is no way to enter the [ ] { } symbols. I get 1/4 and 3/4 symbols instead.

This makes inputting assembly code impossible.

This is on a Mac, but I have been through all possible keyboard combinations (shift, control, option, command) and there is no way to get the square brackets.

**Comment by mattgodbolt** [comment]
Hi: the default BBC Micro display mode is `MODE 7`. This display mode doesn't have those characters, and they are displayed as either a left or right arrow or a ½ symbol. I don't recall ever seeing a ¾ character, but it's been a while.

For example, in mode 7:
![image](https://github.com/mattgodbolt/jsbeeb/assets/633973/aeba47d4-b98e-463f-a732-b02636725ce5)

`LIST`ing the same program in MODE 3:
![image](https://github.com/mattgodbolt/jsbeeb/assets/633973/5fb63bb9-ce2c-4baf-860b-b13e3b4d89c4)

And you'll see it runs fine too, in either mode.

So, I think what you're seeing is the authentic behaviour of the BBC Micro: its default screen mode is not ASCII and has a slightly different character set to the one printed even on its own 1984 keyboard.

Feel free to reopen if you don't think that's quite what you're seeing.

**Comment by mattgodbolt** [comment]
Annnnd of course it had ¼ and ¾ - sorry I just saw them myself by trying each key in turn :) So -- you're right, the 3/4 and 1/4 are shown (but really they're  the squiggly brackets, which you can see if you go into any mode other than 7 and `LIST`)
