### ISSUE TITLE
Tube reset signals not working as expected

### ISSUE THREAD

**Issue by samskivington-poq** [mattgodbolt/jsbeeb#397]
I've raised this before on [stardot forums](https://stardot.org.uk/forums/viewtopic.php?f=4&t=23211).

I'm trying to reset the Tube parasite CPU so that my program can read the start-up banner text - originally an experiment with PiTubeDirect. The code is pulsing bit 5 (P - set parasite reset active low) of &FEE0 high and then low.

I've tried this on a real Beeb and Master (internal and external CoPro both connected) and it works perfectly. In the emulators I've tried to run it on:

BeebEm: resets the parasite CPU but assumes a 65C02 is connected.
B-em: ignores the bit change (this has now been fixed, see stardot link above)
jsBeeb: ignores the bit change

I've put a horribly quick one-liner solution in my local BeebEm because that's the emu I normally use, but it's certainly not fit for inclusion in a PR because atm I only care about getting the Z80 to work.

Could I respectfully ask that the CPU reset (and Tube ULA reset) signals are implemented in jsBeeb please?

**Comment by mattgodbolt** [comment]
Hi @samskivington-poq - thanks for the report! I have little to no experience in the Tube: the support in jsbeeb was mostly a copy-paste-fest and a "does Elite run?" :)

I can't make any promises as to when this will be fixed, but I appreciate the link to stardot, which will help!

**Comment by samskivington-poq** [comment]
Hey. Just following up on my comment on the other one - I've made a couple of tweaks related to the reset, but I'll raise that as a PR once I'm convinced they've actually resolved what they were intended to, correctly vs real hardware without affecting any other part of the Tube emulation. Something doesn't seem right after the reset in that subsequent ULA 'alterations' from the official code seem to behave differently from expected behaviour.

**Comment by samskivington-poq** [comment]
I've made some changes locally that address almost all of the issue, but don't have write access so I can't make a PR for them. Would you like me to show you them here? To be fair, I can't stand Elite (dull, boring game, never understood what all they hype around it was) so I haven't checked that.

**Comment by murkle** [comment]
Try forking your own copy of jsBeeb then you can make the changes there (and make a PR)

**Comment by mattgodbolt** [comment]
You fix should now be live, marking closed (thanks!!)
