### ISSUE TITLE
Loading SSD from local drive

### ISSUE THREAD

**Issue by fizgog** [mattgodbolt/jsbeeb#401]
Just tried to load a local ssd file into JSBeeb and nothing seems to happen.

Choose file from sample or local, the filename shows up, click close

When you *INFO it's still showing the Elite image files

Using JSBeeb on a Mac under either Chrome or Safari (have also cleared the cache)

**Comment by fizgog** [comment]
Just tested under Windows and that's working fine, so it's either just my Mac or all Macs

**Comment by mattgodbolt** [comment]
I spotted this and fixed it a few hours ago!!! Sorry for the confusion: should work ok! sorry for that!

**Comment by mattgodbolt** [comment]
though it could be Macs too...
