### ISSUE TITLE
Arrow keys are not mapped

### ISSUE THREAD

**Issue by patham9** [mattgodbolt/jsbeeb#403]
Playing games like Elite requires arrow keys left and right, as only up and down is mapped to characters.
Hence the current emulator does not allow playing this game on MacOS using any browser as the arrow keys are not recognized.
Is there a workaround for this?

**Comment by mattgodbolt** [comment]
I'm not quite sure what you mean by "only up and down is mapped to characters". I'm able to use all four arrow keys on my Mac. I tested by:

- Booting jsbeeb up https://bbc.godbolt.org/
- Pressing all four cursor keys one at a time
- Observing the cursor moves around on the screen

Is there a way you're testing I can try and reproduce?

**Comment by patham9** [comment]
Ah "," and "." seems to work, sorry for having missed that.

**Comment by mattgodbolt** [comment]
Yes, the keys for elite are a: fire, s&x up/down, ,. left right, slash is faster, space is slower...and many many others too
