### ISSUE TITLE
Tube oops! - copy/paste fail

### ISSUE THREAD

**Issue by SamSkivington** [mattgodbolt/jsbeeb#404]
Hiya.

Whilst writing some robust Tube ULA tests I noticed a failure in my copy/paste skills here:

https://github.com/mattgodbolt/jsbeeb/blob/e78f16d97500d6ff77c4baf8f021a4f446344a6f/tube.js#L222

It _should_ read:

this.hostToParasiteData[TUBE_ULA_R3][this.hostToParasiteFifoByteCount3++] = value;

There's also a comment here that is no longer the case.

https://github.com/mattgodbolt/jsbeeb/blob/e78f16d97500d6ff77c4baf8f021a4f446344a6f/tube.js#L196

Gradually evolving Tube tests SSD is here: https://samskivington.com/public/beeb-discs/tubeTests.ssd

**Comment by codeaholics** [comment]
@mattgodbolt is this related to #421?

**Comment by mattgodbolt** [comment]
Yes! Looks like it's fixed by that... though I'll have to check with the tubeTests.ssd above

**Comment by mattgodbolt** [comment]
@SamSkivington the SSD you linked is no longer available; is it somewhere we can test?

**Comment by mattgodbolt** [comment]
I'm going to close this as fixed as I think it is even though I was unable to test.
