### ISSUE TITLE
Improve 8271 emulation

### ISSUE THREAD

**Issue by murkle** [mattgodbolt/jsbeeb#406]
@mattgodbolt did you see this? https://scarybeastsecurity.blogspot.com/2020/11/reverse-engineering-forgotten-1970s.html

> beebjit now has a much more accurate 8271 driver.

**Comment by mattgodbolt** [comment]
Yes I did! @scarybeasts work is why I filed this...he's been goading me to improve jsbeeb for a while :-) beebjit is an inspiration.

One day!

**Comment by mattgodbolt** [comment]
This is now live! The 8271 implementation is now on par (as best I can tell) with beebjit, including HFE support.
