### ISSUE TITLE
Saving with a co-pro enabled seems to crash jsbeeb/brings up the debugger

### ISSUE THREAD

**Issue by ZornsLemma** [mattgodbolt/jsbeeb#410]
With the current code on [xania.org](https://bbc.xania.org/?coProcessor=true), firing up a BBC B with 65C02 co-pro, leaving the default Elite disc in the drive and doing:
```
*SAVE Z 1000 1100
```
starts to save and then brings up what looks like the jsbeeb debugger:
![Screenshot from 2024-05-17 22-58-57](https://github.com/mattgodbolt/jsbeeb/assets/7988240/61bdc517-1334-486d-8ee8-ea18caf65ee2)

Credit for discovering this goes to Fredrik, who came across it while testing some of my code on jsbeeb over on [stardot](https://stardot.org.uk/forums/viewtopic.php?p=425809#p425809). All errors in this bug report are my own, of course. :-)

This works fine if the co-pro is disabled.

**Comment by mattgodbolt** [comment]
Thanks for the note! repro'd and the culprit is:
```
event noted: exception thrown TypeError: Cannot create property '0' on number '0'
    at dl.parasiteWrite (https://bbc.xania.org/main.ebfd21abafe75f2bc1e8.js:2:261694)
    at Rl.writemem (https://bbc.xania.org/main.ebfd21abafe75f2bc1e8.js:2:289635)
    at n.eval (eval at <anonymous> (https://bbc.xania.org/main.ebfd21abafe75f2bc1e8.js:2:242802), <anonymous>:12:7)
    at n.run (https://bbc.xania.org/main.ebfd21abafe75f2bc1e8.js:2:242866)
    at Rl.execute (https://bbc.xania.org/main.ebfd21abafe75f2bc1e8.js:2:289978)
    at Il.polltimeCommon (https://bbc.xania.org/main.ebfd21abafe75f2bc1e8.js:2:301935)
```

I'll have to dig more to work out what that really is.

**Comment by ZornsLemma** [comment]
Thanks Matt!

**Comment by mattgodbolt** [comment]
Finally taking a look at this. The offending line is:

```js
                    this.parasiteToHostData[TUBE_ULA_R1][this.parasiteToHostFifoByteCount1++] = value;
```

which should be a bunch of FIFOs but has become the number `0`. I'll get this :)

**Comment by mattgodbolt** [comment]
Time to learn how the tube works :)

**Comment by mattgodbolt** [comment]
Or ask "copilot" 👍🏻
![image](https://github.com/user-attachments/assets/370de1f6-f0ae-4ddd-a46a-3375af7d40ca)

**Comment by ZornsLemma** [comment]
Thanks Matt! I'm genuinely impressed with copilot there too...

**Comment by mattgodbolt** [comment]
You and me both! This should be rolling out to the live site now.
