### ISSUE TITLE
Follow text input browser, not keyboard position.

### ISSUE THREAD

**Issue by yqxq** [mattgodbolt/jsbeeb#419]
If you type you need to know on what position characters are on a real Beeb, which is super annoying. Make a toggle to allow 1:1 OS characters to beeb character mapping. So if I type shift 2, you get @ and not "

**Comment by mattgodbolt** [comment]
In the settings (click the name of the computer at the top left e.g. "BBC B With DFS 1.2") you can pick "physical" keys, but it's not a perfect solution. There are plenty of keypresses that can't be properly  mapped.

**Comment by mattgodbolt** [comment]
Sorry I meant "natural" :)

**Comment by mattgodbolt** [comment]
![image](https://github.com/user-attachments/assets/f20f23f7-8c39-471e-9b76-77910f324a43)
