### ISSUE TITLE
Previous screen contents can be left visible in some cases (e.g. Boffin)

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#42]
Play Boffin, then hit break. You end up with a strip of boffin's overscan picture on the far left

**Comment by mattgodbolt** [comment]
@richtw1 - the boffin part seems fixed. Exile goes into "crazy spinning MODE7" screen on break. I'm not sure that's actually wrong; ISTR Exile would sometime do that. Hoping this is all "fixed"

**Comment by richtw1** [comment]
Nope, still not fixed.  Gonna sort it out.

**Comment by richtw1** [comment]
Fixed by e1733b83d1f5a64dacc78a6aacb31899382b139a.
