### ISSUE TITLE
Tube+Master Elite sound sometimes persists

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#44]
http://bbc.godbolt.org/?model=MasterTurbo&disc=sth%3AAcornsoft%2FElite-MasterAndTubeEnhanced.zip&autoboot

Launch, start firing and sometimes the laser sound hangs

**Comment by scarybeasts** [comment]
@mattgodbolt Is this something that used to trigger pretty quickly? I had a quick blast, mounted an ill-advised assault against the Lave space station, and didn't immediately notice any sound hanging.

**Comment by mattgodbolt** [comment]
Yeah this used to happen straight away. I was actually demo'ing Elite on Thursday and used the tube version and was surprised that it worked so well...so...I think this is fixed :)

**Comment by mattgodbolt** [comment]
also lol at "ill-advised assault" -- :)
