### ISSUE TITLE
Teletext `,` char is wrong

### ISSUE THREAD

**Issue by tom-seddon** [mattgodbolt/jsbeeb#447]
I'm not set up to produce PRs for jsbeeb right now, but this is hopefully not too complicated a fix: the bitmap for teletext `,` needs moving down by one scanline.

Photo from real Master 128:

![image](https://github.com/user-attachments/assets/23c232c2-851e-46df-b69c-54ca68d28fb7)

Screen grab from jsbeeb:

![image](https://github.com/user-attachments/assets/b9534478-da7a-4b6e-bae2-ef3c5fc1cc9a)

Note relative placement of bottom of `,` and the horizontal line in the `4`. (I couldn't figure out how to type a `@` in jsbeeb on my US keyboard!)

**Comment by mattgodbolt** [comment]
Oh! Thank you tom!

**Comment by mattgodbolt** [comment]
(`@` is on the backtick ``` key fwiw)!

![image](https://github.com/user-attachments/assets/efb9936a-c183-4f25-aaf0-9b7751cd5e57)

**Comment by mattgodbolt** [comment]
Tom points out that I moved the whole thing down, but there's an issue; the top dots need to stay in the same place.

Also; `@` 's tail is too long and the colon has the same problem.

Maybe worth scraping this:
![image](https://github.com/user-attachments/assets/7f091e90-e364-4ca7-9921-ebc56b93685f)

**Comment by tom-seddon** [comment]
FWIW the changes to be for `;`, `:` and `@` are in this commit: https://github.com/tom-seddon/b2/commit/4e6170c855b531e614f1bfb61b32ac8726944f34
