### ISSUE TITLE
Support ROM urls

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#46]
For e.g. Dr Who (once we find a site that hosts it)

**Comment by BigEd** [comment]
I'd like to run HiBasic and Bas128 - any ideas? I found an ssd with Bas128 on it, so I suppose that's not a ROM problem as such. HiBasic can be found on mdfs.net but only as a ROM image.

**Comment by ahope1** [comment]
Has the "rom" URL parameter been implemented yet?

This doesn't seem to work:

http://bbc.godbolt.org/?rom=https://dl.dropboxusercontent.com/s/6t3agcr48eea9sj/DDOC109

**Comment by mattgodbolt** [comment]
Am on the move but thought it should work; try the beta site perhaps?

**Comment by ahope1** [comment]
Ah, yes. It works in the beta!

http://bbc.godbolt.org/beta/?rom=https://dl.dropboxusercontent.com/s/6t3agcr48eea9sj/DDOC109

**Comment by mattgodbolt** [comment]
Cool! I'll update the main site with the latest beta code. I'd forgotten they weren't in sync!

**Comment by mattgodbolt** [comment]
Main site updated; your original link now works. Leaving this bug open for now to get STH support in...

**Comment by ahope1** [comment]
Thanks! I was trying to work around the problem of Oddjob failing to load in JSBeeb because it requires DFS 1.2 -- I was trying to work around it by creating a custom config using URL-loaded ROMs, but my hack also requires a modified disc image with a custom !BOOT, so it's not ideal:

http://bbc.godbolt.org/?rom=https://dl.dropboxusercontent.com/s/ushwl84l2cdkevz/DNFS&rom=https://dl.dropboxusercontent.com/s/ocqrpii2qkbf2xs/ARM100.ROM&autoboot&disc=https://dl.dropboxusercontent.com/s/bcjnw8em0ugf5q8/Disc103-OddJobD-HAK.ssd

**Comment by BigEd** [comment]
There's probably a URL-poke you could do to disable one of the existing ROMs.
Or maybe the ROM URL interface could allow specifying a slot for the ROM?

**Comment by ahope1** [comment]
Or maybe Matt could fix this issue:

https://github.com/mattgodbolt/jsbeeb/issues/137

;-)

**Comment by ahope1** [comment]
@BigEd You were right about the URL poke. 

Here's a config that includes (1) an unmodified disc image of Oddjob, (2) a URL poke that disables DFS 0.9, and (3) a URL-loaded DFS 1.2 ROM:

http://bbc.godbolt.org/?patch=@ffee,02af:00&rom=https://dl.dropboxusercontent.com/s/ushwl84l2cdkevz/DNFS&autoboot&disc=https://dl.dropboxusercontent.com/s/se37sf4gjqk9ani/Disc103-OddJobD.ssd

I'm using `?(&2A1+romnumber)=0` to disable the DFS 0.9 ROM, assuming it's in slot 14.

**Comment by BigEd** [comment]
nice!

**Comment by scarybeasts** [comment]
@mattgodbolt Can this be closed? Sounds like ROM URLs are implemented, and the question of different DFS options is tracked in the other referenced bug.

**Comment by mattgodbolt** [comment]
Yes I think so! @BigEd / @Pernod70 / @ahope1 feel free to reopen more specific bugs if you find them! Thanks all
