### ISSUE TITLE
Tests fail with vite

### ISSUE THREAD

**Issue by codeaholics** [mattgodbolt/jsbeeb#461]
With commit `4a83d43`, tests fail.

```
% make test

[...]

 Test Files  2 failed | 7 passed (9)
      Tests  7 failed | 35 passed | 2 skipped (44)
   Start at  21:13:09
   Duration  6.41s (transform 222ms, setup 0ms, collect 1.88s, tests 17.93s, environment 1ms, prepare 533ms)
```

All `ENOENT` failures, for example: `Error: ENOENT: no such file or directory, open 'tests/integration/dp111_6502Timing/65C12timing.ssd'`

**Comment by codeaholics** [comment]
Ignore me. I forgot to fetch the submodules. Is there a way to make this easier? Not using submodules, or explicitly checking if they're initialised before running the tests? Or even a test that fails with an explicit error message reminding you to do the submodules dance if the files are missing?

**Comment by codeaholics** [comment]
I opened a PR with a test to ensure the submodules are present and a useful error message if not.

**Comment by mattgodbolt** [comment]
Thanks for chasing this one down!! :)
