### ISSUE TITLE
Support for (read-only) disks on arbitrary URLs

### ISSUE THREAD

**Issue by davidgiven** [mattgodbolt/jsbeeb#52]
So I've just managed to image a floppy disc full of terrible software I wrote 25 years ago. I'd like to make it available online, and your emulator is the simplest and best way to do it.

...unfortunately I can't give people a link to the emulator which points at my disk image. I did try using a Google Drive image but this doesn't work on anonymous users (probably because it needs read-write access).

Ideally something a URL like this would be good: http://bbc.godbolt.org/?disc=http://...blah...

It doesn't sound *too* complicated as sth.js is already doing most of the necessary work. However, I do notice that sth.js seems to be going via a proxy on bbc.godbolt.org; is this because STH doesn't use CORS or is there more to it than that?

**Comment by mattgodbolt** [comment]
Hi! Should be pretty easy to put in arbitrary URL support. And yes the Sth
proxy is due to the CORS issue. I contacted the STH guy but he didn't
respond about adding the headers.

I'll take a look at doing this over the weekend; thanks!


On Saturday, 24 January 2015, David Given <notifications@github.com> wrote:

> So I've just managed to image a floppy disc full of terrible software I
> wrote 25 years ago. I'd like to make it available online, and your emulator
> is the simplest and best way to do it.
>
> ...unfortunately I can't give people a link to the emulator which points
> at my disk image. I did try using a Google Drive image but this doesn't
> work on anonymous users (probably because it needs read-write access).
>
> Ideally something a URL like this would be good:
> http://bbc.godbolt.org/?disc=http://...blah...
>
> It doesn't sound *too* complicated as sth.js is already doing most of the
> necessary work. However, I do notice that sth.js seems to be going via a
> proxy on bbc.godbolt.org; is this because STH doesn't use CORS or is
> there more to it than that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/jsbeeb/issues/52>.
>


-- 
Via phone: excuse typos

**Comment by mattgodbolt** [comment]
Can you give this a spin on http://bbc.godbolt.org/beta?disc=http://your.url.here/ ? It will need CORS stuff set up: if it doesn't work you'll get an error, check the JS console for more details.

Let me know how you get on!

**Comment by davidgiven** [comment]
I don't have CORS set up yet, but after running chrome with --disable-web-security (which is alleged to bypass it), it doesn't seem to work --- I can see it access the URL, and I can see it download 200kB of data, but then the emulated BBC just sees an empty disk.

However as I don't have the CORS stuff set up right yet I'm not entirely convinced that this was a fair test. I'll try and make that work and get back to you.

**Comment by mattgodbolt** [comment]
Thanks for checking; in honesty I've probably still got an issue on my
side. I hacked it together in 10 mins before heading out! I'll take another
look in a few hours' time. Sorry for the trouble!

On Sunday, 25 January 2015, David Given <notifications@github.com> wrote:

> I don't have CORS set up yet, but after running chrome with
> --disable-web-security (which is alleged to bypass it), it doesn't seem to
> work --- I can see it access the URL, and I can see it download 200kB of
> data, but then the emulated BBC just sees an empty disk.
>
> However as I don't have the CORS stuff set up right yet I'm not entirely
> convinced that this was a fair test. I'll try and make that work and get
> back to you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/jsbeeb/issues/52#issuecomment-71383675>.
>


-- 
Via phone: excuse typos

**Comment by mattgodbolt** [comment]
Yup; I tried it and it doesn't work (thanks for the --disable-web-security tip!)

**Comment by mattgodbolt** [comment]
If you confirm this works for the beta site I'll update the non-beta site too :)

**Comment by davidgiven** [comment]
Works beautifully. Thanks!

**Comment by mattgodbolt** [comment]
Glad to hear it! I've updated the main bbc.godbolt.org site with the latest
code so it should work there too!  If yu have any issues with the CORS or
similar I can help if needed!
