### ISSUE TITLE
Video emulation too sensitive to sync width

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#55]
(Reported by Richard Broahurst)

The video code is now so sensitive that you cannot use different h-sync pulse widths within the same screen without losing two thirds of the display.

Richard has a demo http://www.retrosoftware.co.uk/forum/viewtopic.php?f=19&t=903&hilit=rally#p6607 that allows the h-sync pulse settings to be altered while moving the map with the cursor keys. If you press a key on the top row (Q..U) it adjusts the odd (or even-can't remember) horizontal half character position and the middle row (A..H) it adjusts the other half char offset, the idea is to make them half a char apart on screen so that when scrolling the 31 and a half chars displayed doesn't move from side to side, but just scrolls smoothly. The bottom row (Z..M) moves the v-ruptured status block at the bottom to try to reduce the blurring/bouncing of the top of the 1UP, radar box and 2UP. The beeb default setting is achieved by pressing UAV, but smooth scrolling requires USB or USV (matching U or S) so that every other frame is either aligned or miss-aligned by half a character. On my most sensitive CRT, I can only use YAC (minimum control panel judder), USV or USB which both have slightly more judder on the first couple of scan lines on the 1UP, top of the radar and 2UP.

With any of the three settings mentioned above, there seems to be a copy of the second line of the control panel visible above the first line of the control panel. This may be a bug in Richard's code that doesn't show up on a real CRT, but it does seem strange.

**Comment by richtw1** [comment]
Fixed by e1733b83d1f5a64dacc78a6aacb31899382b139a.
