### ISSUE TITLE
Add a "run at full speed" setting

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#56]
As in, no delay at all. Also maybe % of real time.

**Comment by BigEd** [comment]
Would this speed up cassette loading? I was playing with Acornsoft Lisp which takes minutes to load - and I can't even background the tab, or it stalls!
http://bbc.godbolt.org/?tape=sth%3Alang%2FAcornsoft%2FLisp_B.zip&autochain

**Comment by mattgodbolt** [comment]
Whoops: tape loading is supposed to continue even when in a separate tab. Speed tape loading is definitely something I have on my to-do list: lots of it comes down to not doing video processing as often as most of the hard work is really the video emulation: running at "full speed" on my pretty beefy laptop is still only ~2x faster in my experiments, so more needs to be done. For a laugh you can try the "cpuMultiplier" on the beta site, e.g. 
http://bbc.godbolt.org/beta/?tape=sth%3Alang%2FAcornsoft%2FLisp_B.zip&cpuMultiplier=2 (autochain appears broken at the moment so you'll need to type *TAPE etc)

**Comment by BigEd** [comment]
Hmm, the beta version froze when not the front tab, and failed to unfreeze when displayed again.

**Comment by mattgodbolt** [comment]
Oops; seems like I've broken some things there. Will investigate: thanks.

**Comment by scarybeasts** [comment]
These days, "as fast as possible" is about 3x on my rubbish old laptop.

Rather than lowering emulation accuracy in fasttape mode, I might look to see if there are any generic speedups available in either the CPU or video code.

**Comment by mattgodbolt** [comment]
That's great: thanks @scarybeasts !
