### ISSUE TITLE
Issue with mid-screen mode changes

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#58]
From Richard Broadhurst:

"I noticed what seems to be a new bug.

When I do a vertical rupture, the last row of pixels on the top screen is repeated over the first row on the bottom screen. On the new version of AstroBlaster that I have just posted to *. you can see it sometimes repeating and sometimes not as the timing goes back and fore.

I thought it was related to the horizontal sync pulse width as I had only seen it on my Rally-X demo, but it is now visible on AstroBlaster which doesn't change the h-sync pulse width."

**Comment by richtw1** [comment]
Fixed by e1733b83d1f5a64dacc78a6aacb31899382b139a.
