### ISSUE TITLE
Frogman has stopped working!!!

### ISSUE THREAD

**Issue by richtw-epic** [mattgodbolt/jsbeeb#60]
Stupid amphibian!

**Comment by richtw-epic** [comment]
EORloop madness is failing on BBC B / Master, i.e. even before the page &E00 corruption fails it on a BBC B.

http://bbc.godbolt.org/beta/?disc=sth%3AUnreleased%2FFrogman-demo.zip

![image](https://cloud.githubusercontent.com/assets/9282827/8479461/4045c106-20d8-11e5-902f-59e0e5033b89.png)

**Comment by mattgodbolt** [comment]
Argh! No way! I wonder what on earth's going on there...will have to do a
binary search to see where it got broken.

On Thu, Jul 2, 2015 at 9:34 AM, Richard Talbot-Watkins <
notifications@github.com> wrote:

> EORloop madness is failing on BBC B / Master, i.e. even before the page
> &E00 corruption fails it on a BBC B.
>
> http://bbc.godbolt.org/beta/?disc=sth%3AUnreleased%2FFrogman-demo.zip
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/9282827/8479461/4045c106-20d8-11e5-902f-59e0e5033b89.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/jsbeeb/issues/60#issuecomment-118051654>.
>



-- 
Matt

**Comment by mattgodbolt** [comment]
Hmm it just "worked for me". I used an autoboot URL:
http://bbc.godbolt.org/beta/?disc=sth%3AUnreleased%2FFrogman-demo.zip&autoboot
I wonder if that's it. Did you shift-break it?

On Thu, Jul 2, 2015 at 9:41 AM, Matt Godbolt <matt@godbolt.org> wrote:

> Argh! No way! I wonder what on earth's going on there...will have to do a
> binary search to see where it got broken.
>
> On Thu, Jul 2, 2015 at 9:34 AM, Richard Talbot-Watkins <
> notifications@github.com> wrote:
>
>> EORloop madness is failing on BBC B / Master, i.e. even before the page
>> &E00 corruption fails it on a BBC B.
>>
>> http://bbc.godbolt.org/beta/?disc=sth%3AUnreleased%2FFrogman-demo.zip
>>
>> [image: image]
>> <https://cloud.githubusercontent.com/assets/9282827/8479461/4045c106-20d8-11e5-902f-59e0e5033b89.png>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mattgodbolt/jsbeeb/issues/60#issuecomment-118051654>.
>>
>
>
>
> --
> Matt
>



-- 
Matt

**Comment by mattgodbolt** [comment]
Confirmed that shift-breaking doesn't work, but autoboot does. Hmm

On Thu, Jul 2, 2015 at 9:43 AM, Matt Godbolt <matt@godbolt.org> wrote:

> Hmm it just "worked for me". I used an autoboot URL:
> http://bbc.godbolt.org/beta/?disc=sth%3AUnreleased%2FFrogman-demo.zip&autoboot
> I wonder if that's it. Did you shift-break it?
>
> On Thu, Jul 2, 2015 at 9:41 AM, Matt Godbolt <matt@godbolt.org> wrote:
>
>> Argh! No way! I wonder what on earth's going on there...will have to do a
>> binary search to see where it got broken.
>>
>> On Thu, Jul 2, 2015 at 9:34 AM, Richard Talbot-Watkins <
>> notifications@github.com> wrote:
>>
>>> EORloop madness is failing on BBC B / Master, i.e. even before the page
>>> &E00 corruption fails it on a BBC B.
>>>
>>> http://bbc.godbolt.org/beta/?disc=sth%3AUnreleased%2FFrogman-demo.zip
>>>
>>> [image: image]
>>> <https://cloud.githubusercontent.com/assets/9282827/8479461/4045c106-20d8-11e5-902f-59e0e5033b89.png>
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/mattgodbolt/jsbeeb/issues/60#issuecomment-118051654>
>>> .
>>>
>>
>>
>>
>> --
>> Matt
>>
>
>
>
> --
> Matt
>



-- 
Matt

**Comment by mattgodbolt** [comment]
It just seems intermittant actually. Will dig more!

On Thu, Jul 2, 2015 at 9:43 AM, Matt Godbolt <matt@godbolt.org> wrote:

> Confirmed that shift-breaking doesn't work, but autoboot does. Hmm
>
> On Thu, Jul 2, 2015 at 9:43 AM, Matt Godbolt <matt@godbolt.org> wrote:
>
>> Hmm it just "worked for me". I used an autoboot URL:
>> http://bbc.godbolt.org/beta/?disc=sth%3AUnreleased%2FFrogman-demo.zip&autoboot
>> I wonder if that's it. Did you shift-break it?
>>
>> On Thu, Jul 2, 2015 at 9:41 AM, Matt Godbolt <matt@godbolt.org> wrote:
>>
>>> Argh! No way! I wonder what on earth's going on there...will have to do
>>> a binary search to see where it got broken.
>>>
>>> On Thu, Jul 2, 2015 at 9:34 AM, Richard Talbot-Watkins <
>>> notifications@github.com> wrote:
>>>
>>>> EORloop madness is failing on BBC B / Master, i.e. even before the page
>>>> &E00 corruption fails it on a BBC B.
>>>>
>>>> http://bbc.godbolt.org/beta/?disc=sth%3AUnreleased%2FFrogman-demo.zip
>>>>
>>>> [image: image]
>>>> <https://cloud.githubusercontent.com/assets/9282827/8479461/4045c106-20d8-11e5-902f-59e0e5033b89.png>
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/mattgodbolt/jsbeeb/issues/60#issuecomment-118051654>
>>>> .
>>>>
>>>
>>>
>>>
>>> --
>>> Matt
>>>
>>
>>
>>
>> --
>> Matt
>>
>
>
>
> --
> Matt
>



-- 
Matt

**Comment by mattgodbolt** [comment]
Traced back to the even/odd cycle counter for bus stretching being affecting by an odd number of CPU cycles being passed to "cpu.execute(cycles)". Will come up with a fix later!
