### ISSUE TITLE
Correct 65C12 emulation

### ISSUE THREAD

**Issue by richtw1** [mattgodbolt/jsbeeb#68]
Hardly a biggy, but there are a few errors:
- JMP (indirect) takes an extra cycle
- RMW instructions perform an extra read instead of an extra write
- Check timings of (zp) addressing mode (should be 5 cycles)
- ASL LSR ROL ROR abs,X take a cycle less when page not crossed
- Handle invalid opcodes in a similar way to 6502, and correct timings.
- Extra cycle to fix up flags for ADC/SBC in decimal mode (already done I think)
- Automatically clear D flag on entry to IRQ/NMI

**Comment by BigEd** [comment]
Some of these, but not all, are done now, I think. Is it the case that both of 65SC12 and 65C102 are needed, but are pretty much the same? The first is CMD/GTE and is the Master's own and the second Rockwell and is in the Turbo board. Datasheets can be found at http://6502.org/documents/datasheets/

**Comment by mattgodbolt** [comment]
I think all these are now accounted for. Closing - please reopen if anyone disagrees. FWIW quick way to check an instruction:

    require('6502.opcodes').cpu65c12().getInstruction("LDA ()").join("\n")

replace the instruction as needed and `cpu6502` for 6502 variants etc.

**Comment by mattgodbolt** [comment]
@BigEd I haven't modeled the sc12 vs c102 in jsbeeb -- if there's anything compelling different for the Turbo we should open a new bug to track those differences...

**Comment by BigEd** [comment]
OK! In part I left that record to help searching.

**Comment by mattgodbolt** [comment]
Perfect! Thanks :)

**Comment by tom-seddon** [comment]
jsbeeb doesn't appear to handle the all of the CMOS NOPs - in particular, the 1-byte 1-cycle ones seem to be missing.

There's a NOPs table at the bottom of this page: http://6502.org/tutorials/65c02opcodes.html - I haven't tested this stuff at all thoroughly, but opcode $03 definitely takes just 1 cycle on my Master 128.

Thanks,

--Tom

**Comment by mattgodbolt** [comment]
Ooh thanks Tom!

**Comment by tom-seddon** [comment]
I've done some testing on Master 128 (65C12), 6502 second processor (Rockwell 65c02) and ReCoMini6502 (WDC 65c02), and the NOPs table appears to be accurate for all of them.

There's some info here about what the CMOS NOPs actually do internally: http://laughtonelectronics.com/Arcana/KimKlone/Kimklone_opcode_mapping.html

--Tom

**Comment by mattgodbolt** [comment]
> jsbeeb doesn't appear to handle the all of the CMOS NOPs - in particular, the 1-byte 1-cycle ones seem to be missing.

I _think_ it does handle (most of) them. Any undoc'd instruction hits `invalidOpcode()`. For `is65c12` all opcodes are treated as NOPs, default case is the one cycle (the instruction fetch that already happened). Special cases are added for the `0x*2` and some `0x*4` and `0x*c`s.

There's definitely some missing ones, so I'll add them

**Comment by mattgodbolt** [comment]
Added the missing ones...Tom, by any chance do you happen to have a wee test program around from your tests that I could use to shore up my testing?

**Comment by tom-seddon** [comment]
Sure - do a Shift+Break on this disk image: [nops.zip](https://github.com/mattgodbolt/jsbeeb/files/3327030/nops.zip) - it'll check the opcode timings and print any unexpected results with a red background.

Results from my Master 128.

![image](https://user-images.githubusercontent.com/1269020/60128759-53947f80-978b-11e9-8403-27595e278b8b.png)

Results from my ReCoMini6502. I think these are going to be mostly the same as a Master Turbo? - one definite exception is opcodes $cb and $db, which aren't NOPs on the WDC 65c02 but are on the Rockwell CPUs.
 
![image](https://user-images.githubusercontent.com/1269020/60128973-e2090100-978b-11e9-8d87-dcfcc373a79f.png)

--Tom

**Comment by mattgodbolt** [comment]
you're the best Tom!

**Comment by mattgodbolt** [comment]
![Screenshot from 2019-06-25 16-56-08](https://user-images.githubusercontent.com/633973/60136584-2edbe000-976a-11e9-9882-8c6fdbae1771.png)

(from the live site)

**Comment by mattgodbolt** [comment]
Getting there:
![Screenshot from 2019-06-25 17-20-25](https://user-images.githubusercontent.com/633973/60137737-8a5b9d00-976d-11e9-976a-197d6c0b8bf8.png)

**Comment by mattgodbolt** [comment]
The crash comes from the fact I have `0xcb` => `WAI` which is another BRK instruction. I suspect this is a hangover from me taking C64 CPU results...

**Comment by mattgodbolt** [comment]
Yay 
![Screenshot from 2019-06-25 17-25-29](https://user-images.githubusercontent.com/633973/60137969-40bf8200-976e-11e9-8495-4692f4574058.png)

**Comment by mattgodbolt** [comment]
Leaving this open until I get an automated test for this =)

**Comment by mattgodbolt** [comment]
Gah, I have half the code written, but ran out of concentration:) Stupid CppCon...will return to this when I can (sometime late September...)

**Comment by mattgodbolt** [comment]
woo actually done. Not all that happy but I have something of a framework to start improving from.
