### ISSUE TITLE
Turn off interlace

### ISSUE THREAD

**Issue by murkle** [mattgodbolt/jsbeeb#76]
Zalaga looks terrible when you move the ship

(I don't think there's even any need to have an option, probably fine for everything to just turn it off)

**Comment by richtw1** [comment]
Done that, but it's a part of a whole bunch of video emulation fixes I'm doing when I ever have a chance!

**Comment by richtw1** [comment]
Closed by e1733b83d1f5a64dacc78a6aacb31899382b139a.
