### ISSUE TITLE
Option for shift-break on menu + url

### ISSUE THREAD

**Issue by stuaxo** [mattgodbolt/jsbeeb#80]
This way we can share URLs that load a disk image.

**Comment by stuaxo** [comment]
Ah, just found "autoboot" - it would be great if this was an extra button on the load disk image dialog.

**Comment by mattgodbolt** [comment]
Mostly a duplicate of #39 ... will fix!

**Comment by mattgodbolt** [comment]
Done and site updated. Thanks for the suggestion!

On Sat, Aug 29, 2015 at 7:18 AM, Stuart Axon <notifications@github.com>
wrote:

> Ah, just found "autoboot" - it would be great if this was an extra button
> on the load disk image dialog.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/jsbeeb/issues/80#issuecomment-135980190>.
>



-- 
Matt
