### ISSUE TITLE
iPad mini bugs

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#85]
(via Anthony Hope)

"So I finally upgraded to iOS 8 on my iPad Mini 2, and at last I can run jsbeeb in the Mobile Safari browser. Only one snag -- no keyboard!

Is there some special tweak that needs to be made for iOS so that your in-browser emulator "captures" input from the iOS keyboard?"

and

"I just found that sound doesn't seem to work on my iPad Mini 2, at least not with this disc image: http://bbc.godbolt.org/?autoboot&disc=https%3A%2F%2Fs3.amazonaws.com%2Fbeeb%2FFireTrack.ssd
"

**Comment by ahope1** [comment]
Matt, thanks for adding this. 

Re the lack of sound, I just noticed that when I load JSBeeb on my iPad Mini 2 (iOS 8.4), any audio playing on the device stops, so maybe JSBeeb is grabbing the sound output stream but isn't actually using it for some reason.

**Comment by mattgodbolt** [comment]
Thanks: I'm sorry I still haven't got to this...I'll be honest I first have
to crowbar the iPad off of my wife, and then work out how on earth to debug
it :)

On Sun, Sep 13, 2015 at 8:47 AM, Ant <notifications@github.com> wrote:

> Matt, thanks for adding this.
>
> Re the lack of sound, I just noticed that when I load JSBeeb on my iPad
> Mini 2 (iOS 8.4), any audio playing on the device stops, so maybe JSBeeb is
> grabbing the sound output stream but isn't actually using it for some
> reason.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/jsbeeb/issues/85#issuecomment-139878195>.
>



-- 
Matt

**Comment by murkle** [comment]
simple iPad console:
<script src="http://getfirebug.com/releases/lite/1.2/firebug-lite-compressed.js">
(or a later version, this worked for me :)

**Comment by mattgodbolt** [comment]
Thanks @murkle . My wife's away this weekend, I might even get a chance to look at it if the kids give me a break :)

**Comment by MrSimmo** [comment]
Hi Matt,

Echo this on an iPad Air 2 and iPhone X. I guess theres two issues being discussed here, so keyboard I've sent a question in the other thread, hope thats ok? 

I'm also trying to use a Logitech Ultrathin Bluetooth keyboard with my iPad (IOS 11.2.1), it does type but key repeat gets stuck on as soon as you type a character. What do you reckon?

In terms of sound, I also get no sound across IOS devices. Do you reckon this would be easy to fix?


Btw - loving JSBeeb - this is taking me back to my school days. I've already taken it to show my dad (who is now long retired) who cringes when he hears the Repton 3 music!!


Cheers, Andy

**Comment by mattgodbolt** [comment]
As I understand it one only gets sound if you've pressed a button, or something like that. I don't really know...I need to take a look sometime, but I'm woefully inadequately set up for tablet development (I don't know how you debug such things!)

Re: typing...I have literally no idea. jsbeeb looks for the JS key down and key up events. If I don't get the key up event then the key will be "stuck" down.

**Comment by MrSimmo** [comment]
No worries, I know the feeling! My tablet dev skills are atrocious ! 

Hmm ok - I'll see if I can find a way to debug and keep you posted

**Comment by ahope1** [comment]
We should probably close [this](https://github.com/mattgodbolt/jsbeeb/issues/85).

Duplicate of #186 and #114.

**Comment by mattgodbolt** [comment]
Closing per @ahope1 's suggestion. Hopefully it's a _little_ bit better now
