### ISSUE TITLE
Support Paste, and maybe Copy, for character input/output

### ISSUE THREAD

**Issue by BigEd** [mattgodbolt/jsbeeb#86]
Perhaps if we had a textual console as an option we could get both copy and paste fairly readily?

For extra points, consider using the teletext web font as seen on stardot!

One of the other beeb emulators offers a text-mode input/output option for accessibility reasons.

Feel free to reject this, telling me to run in node.js instead!

Another possible implementation: offer a text-mode i/o for the serial port. The intrepid can issue *fx2,1 and *fx3,5 to drive the machine through it.

**Comment by mattgodbolt** [comment]
Great idea Ed! Which emulator had you seen: I'm interested to see how copy would be achieved. I get how pasting in would work, though I kinda see how I can hook oswrch to get some output out...

**Comment by BigEd** [comment]
Away from keyboard until Monday but it might be
http://b-em.bbcmicro.com

**Comment by BigEd** [comment]
Sorry, no, it's
http://www.mkw.me.uk/beebem/index.html
See the Copy and Paste menu entries under Edit, but more interesting perhaps the Screen Reader Text View feature in the View menu. Which isn't presently working for me, but I've seen it working before.

**Comment by scarybeasts** [comment]
We now have initial paste support, courtesy of: https://github.com/mattgodbolt/jsbeeb/issues/164

I'm going to be opinionated and suggest that copy is probably a big lift to implement in any way, hence closing.

There are a lot of different ways to consider implementing getting I/O into and out of jsbeeb. For me personally, a virtual serial connection seems appealing, e.g. enable RS432 I/O on the beeb and attach a web text area at the other end? I don't have plans to work on this at this time, though.
