### ISSUE TITLE
loadBasic causes screen corruption and Bad Program

### ISSUE THREAD

**Issue by BigEd** [mattgodbolt/jsbeeb#87]
Trying to use the loadBasic URL interface to load a public gist, I find that an error in the program (syntax or similar) causes Bad Program and sometimes screen corruption.

See for example
http://bbc.godbolt.org/?autorun&loadBasic=https://gist.githubusercontent.com/BigEd/e9e28718eb3205a42221/raw/93bec7c5b2ca4f26948d2da2b71b768883fb49d3/sieve-c64

**Comment by murkle** [comment]
Another test-case:
http://bbc.godbolt.org/?autorun&loadBasic=https://test.geogebra.org/~mike/Rheolism.txt

which says "missing ,"

(from http://survex.com/~olly/rheolism/dsm_rheolism/ )

**Comment by BigEd** [comment]
Indeed, something's not right with that - on another emulator, that program is rejected with No such variable.

As a further case, here's the Beeb version of rheolism, which starts up OK but gets stuck before the first piece falls:
http://bbc.godbolt.org/?autorun&loadBasic=https://gist.githubusercontent.com/BigEd/1ac1c0ea898886551675/raw/1a434f1c9f3e51c263ca0887766f1256ca0987e9/rheolism-beeb
Or it fails with a spurious error on line 7.

This is what I believe should happen:
http://bbc.godbolt.org/?patch=@bc09,3e0:324f4c440d4c492e0d52454d204e4f5720545950452052554e2120202020200d;@bc09,2d8:e1;@e4e0,1900:0D00002D643D643AE76420EF643A703DB036342AB12C3145332DBC2A3332293AF8208BEB323AE6302C2D393ADA0D000138643D393AF5EF33303AF5E4A33AE7B13D3135EF32382C352CBC2C31343B31312C32363AE7308BE7703D30F13AFD308BFDBC3D32350D000217623D94B32083373A6B3D303AEF33312C392C330D00030DF5673D392DA63683330D000413E36C3DB920B8313A6F3D6C2080B46F0D000524E76F3D6C20FB622D31353AEF6C2082673A6B3D6B2B28673D3780392D362A6C290D00061BE7308BE3663D30B831313A643D662F33843282643AE4A30D000738E7325E2828662B6B2983313229803937358026433235393045432F385E6220EF323038302A946C3B3A6F3D6F2B703AE7308BED2C0D000810EF32303AFD6F2AAB673AFD300DFF39

**Comment by mattgodbolt** [comment]
rheolism is kinda special as IIRC you could never actually type it in
as-is: there were some ambiguous tokenisations or something. Will take a
look though :)

On Wed, Sep 30, 2015 at 4:39 AM, BigEd <notifications@github.com> wrote:

> Indeed, something's not right with that - on another emulator, that
> program is rejected with No such variable.
>
> As a further case, here's the Beeb version of rheolism, which starts up OK
> but gets stuck before the first piece falls:
>
> http://bbc.godbolt.org/?autorun&loadBasic=https://gist.githubusercontent.com/BigEd/1ac1c0ea898886551675/raw/1a434f1c9f3e51c263ca0887766f1256ca0987e9/rheolism-beeb
> Or it fails with a spurious error on line 7.
>
> This is what I believe should happen:
> http://bbc.godbolt.org/?patch=@bc09,3e0:324f4c440d4c492e0d52454d204e4f5720545950452052554e2120202020200d;@bc09,2d8:e1;@e4e0,1900:0D00002D643D643AE76420EF643A703DB036342AB12C3145332DBC2A3332293AF8208BEB323AE6302C2D393ADA0D000138643D393AF5EF33303AF5E4A33AE7B13D3135EF32382
> C352CBC2C31343B31312C32363AE7308BE7703D30F13AFD308BFDBC3D32350D000217623D94B32083373A6B3D303AEF33312C392C330D00030DF5673D392DA63683330D000413E36C3DB920B8313A6F3D6C2080B46F0D000524E76F3D6C20FB622D31353AEF6C2082673A6B3D6B2B28673D3780392D362A6C290D00061BE7308BE3663D30B831313A643D662F33843282643AE4A30D000738E7325E2828662B6B2983313229803937358026433235393045432F385E6220EF323038302A946C3B3A6F3D6F2B703AE7308BED2C0D000810EF32303AFD6F2AAB673AFD300DFF39
> <http://bbc.godbolt.org/?patch=@bc09,3e0:324f4c440d4c492e0d52454d204e4f5720545950452052554e2120202020200d;@bc09,2d8:e1;@e4e0,1900:0D00002D643D643AE76420EF643A703DB036342AB12C3145332DBC2A3332293AF8208BEB323AE6302C2D393ADA0D000138643D393AF5EF33303AF5E4A33AE7B13D3135EF32382C352CBC2C31343B31312C32363AE7308BE7703D30F13AFD308BFDBC3D32350D000217623D94B32083373A6B3D303AEF33312C392C330D00030DF5673D392DA63683330D000413E36C3DB920B8313A6F3D6C2080B46F0D000524E76F3D6C20FB622D31353AEF6C2082673A6B3D6B2B28673D3780392D362A6C290D00061BE7308BE3663D30B831313A643D662F33843282643AE4A30D000738E7325E2828662B6B2983313229803937358026433235393045432F385E6220EF323038302A946C3B3A6F3D6F2B703AE7308BED2C0D000810EF32303AFD6F2AAB673AFD300DFF39>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/jsbeeb/issues/87#issuecomment-144339646>.
>



-- 
Matt

**Comment by mattgodbolt** [comment]
Ok I take that back: I think rheolism was supposed to be type-innable.

**Comment by mattgodbolt** [comment]
If one omits the "autorun" from the URL and then types LIST there's clearly some problems (now captured in #88).

Also if you type "LIST" before running the program it fixes it up enough to just about work. I bet my basic patcher doesn't quite do what running "OLD" does...

**Comment by mattgodbolt** [comment]
I thought I'd fixedf this with my fixes for #88, but rheolism now actually
puts the (now native) tokeniser into an infinite loop (oops).  We'll get
there eventually :)

On Wed, Sep 30, 2015 at 8:01 AM, Matt Godbolt <matt@godbolt.org> wrote:

> rheolism is kinda special as IIRC you could never actually type it in
> as-is: there were some ambiguous tokenisations or something. Will take a
> look though :)
>
> On Wed, Sep 30, 2015 at 4:39 AM, BigEd <notifications@github.com> wrote:
>
>> Indeed, something's not right with that - on another emulator, that
>> program is rejected with No such variable.
>>
>> As a further case, here's the Beeb version of rheolism, which starts up
>> OK but gets stuck before the first piece falls:
>>
>> http://bbc.godbolt.org/?autorun&loadBasic=https://gist.githubusercontent.com/BigEd/1ac1c0ea898886551675/raw/1a434f1c9f3e51c263ca0887766f1256ca0987e9/rheolism-beeb
>> Or it fails with a spurious error on line 7.
>>
>> This is what I believe should happen:
>> http://bbc.godbolt.org/?patch=@bc09,3e0:324f4c440d4c492e0d52454d204e4f5720545950452052554e2120202020200d;@bc09,2d8:e1;@e4e0,1900:0D00002D643D643AE76420EF643A703DB036342AB12C3145332DBC2A3332293AF8208BEB323AE6302C2D393ADA0D000138643D393AF5EF33303AF5E4A33AE7B13D3135EF32382
>> C352CBC2C31343B31312C32363AE7308BE7703D30F13AFD308BFDBC3D32350D000217623D94B32083373A6B3D303AEF33312C392C330D00030DF5673D392DA63683330D000413E36C3DB920B8313A6F3D6C2080B46F0D000524E76F3D6C20FB622D31353AEF6C2082673A6B3D6B2B28673D3780392D362A6C290D00061BE7308BE3663D30B831313A643D662F33843282643AE4A30D000738E7325E2828662B6B2983313229803937358026433235393045432F385E6220EF323038302A946C3B3A6F3D6F2B703AE7308BED2C0D000810EF32303AFD6F2AAB673AFD300DFF39
>> <http://bbc.godbolt.org/?patch=@bc09,3e0:324f4c440d4c492e0d52454d204e4f5720545950452052554e2120202020200d;@bc09,2d8:e1;@e4e0,1900:0D00002D643D643AE76420EF643A703DB036342AB12C3145332DBC2A3332293AF8208BEB323AE6302C2D393ADA0D000138643D393AF5EF33303AF5E4A33AE7B13D3135EF32382C352CBC2C31343B31312C32363AE7308BE7703D30F13AFD308BFDBC3D32350D000217623D94B32083373A6B3D303AEF33312C392C330D00030DF5673D392DA63683330D000413E36C3DB920B8313A6F3D6C2080B46F0D000524E76F3D6C20FB622D31353AEF6C2082673A6B3D6B2B28673D3780392D362A6C290D00061BE7308BE3663D30B831313A643D662F33843282643AE4A30D000738E7325E2828662B6B2983313229803937358026433235393045432F385E6220EF323038302A946C3B3A6F3D6F2B703AE7308BED2C0D000810EF32303AFD6F2AAB673AFD300DFF39>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mattgodbolt/jsbeeb/issues/87#issuecomment-144339646>.
>>
>
>
>
> --
> Matt
>



-- 
Matt

**Comment by richtw1** [comment]
Yeah it's too long to type on one line (exceeds the BASIC line buffer length) but fits ok once tokenized (try it!).  Only way to enter that is to poke it into memory directly!

**Comment by richtw1** [comment]
Also, to add, the commented out version in the test code is in BASIC V!

**Comment by mattgodbolt** [comment]
Reopening as Ed's original still doesn't work properly. Probably due to my dodgy BASIC pokery that tries to avoid an "OLD" being needed.

http://bbc.godbolt.org/beta/?loadBasic=https://gist.githubusercontent.com/BigEd/e9e28718eb3205a42221/raw/93bec7c5b2ca4f26948d2da2b71b768883fb49d3/sieve-c64 

Running "OLD" first "fixes" it.

**Comment by mattgodbolt** [comment]
Fixed for reals this time by 65fa954a23e185262d3d4a0e282df04ba2e30810

**Comment by ahope1** [comment]
@BigEd Can you please explain how your patch works in [your comment above](https://github.com/mattgodbolt/jsbeeb/issues/87#issuecomment-144339646)? What's the significance of the memory addresses &BC09, &3E0 and &2D8?

**Comment by BigEd** [comment]
It's been a while! Here's my best guess: BC09 is a trigger address which the PC hits when Basic is more or less ready to take input. 3E0 is the address of the input buffer and 2D8 is the length of the stuff in the buffer. E4E0 is a trigger address which the PC hits when the OS has finished initialising memory, so we can pre-load a binary to 1900.
Why both loaded a binary and stuff the input buffer? I think that's to issue an OLD and a LIST and the REM Now Type Run instruction.

**Comment by ahope1** [comment]
@BigEd Thanks! But I don't think I fully understand the value that goes into 2D8. In the following URL, for example, the buffer is fairly small, and yet 2D8 still has to be poked with E1 for everything to work properly:

http://bbcmicro.co.uk/jsbeeb/play.php?disc=http://bbcmicro.co.uk//gameimg/discs/Disc079-GetSetSantaE.ssd&patch=@bc09,3e0:324f4c440d52554e0d000d;@bc09,2d8:e1;@e4e0,1900:0d00000f2a455845432021424f4f540dff

**Comment by BigEd** [comment]
Perhaps not so much a length as a pointer? See
http://mdfs.net/Docs/Comp/BBC/AllMem
`&02D8-&02E0 Buffer start indexes`

**Comment by ahope1** [comment]
@BigEd Yes, I had seen that reference but I didn't really understand it! But according to [this doc](http://ininet.org/the-advanced-user-guide-for-the-acorn-electron.html?page=14), 2D8 is the buffer-start offset and 2E1 is the buffer-end offset, so here's the correct version of my previous URL:

http://bbcmicro.co.uk/jsbeeb/play.php?disc=http://bbcmicro.co.uk//gameimg/discs/1410/Disc079-GetSetSantaE.ssd&patch=@bc09,3e0:4f4c440d52554e0d;@bc09,2d8:e0;@bc09,2e1:e8;@e4e0,1900:0d00000f2a455845432021424f4f540dff
