### ISSUE TITLE
Basic tokenizer bugs

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#88]
cf #87 - the `"CALCULATION TOOK"` string is turned into "CALCULATIn 80K" somehow (hahah) - clearly doesn't take into account strings, also the "JIFFY" becomes tokenised too.

**Comment by richtw1** [comment]
Yeah naive pattern-matching won't work.  Each keyword has a bunch of flags which determine the context in which it should be tokenized.

Here's a disassembly and explanation of BASIC 4's tokenization routine: http://8bs.com/basic/basic4-8db2.htm

And here's the keyword table with an explanation of the flags assigned to each entry:
http://8bs.com/basic/basic4-8456.htm

**Comment by mattgodbolt** [comment]
Reopening to capture @richtw1 's comment

**Comment by mattgodbolt** [comment]
Ok I think I've licked this one for now - now uses the emulator itself to tokenise
