### ISSUE TITLE
Stop display flicker/spam when pressing Break.

### ISSUE THREAD

**Issue by richtw1** [mattgodbolt/jsbeeb#90]
Shouldn't be blatting rubbish over the canvas when Break is pressed.  Don't reset so much stuff on Reset, in particular the Video class internals.  Might fix it.  Same goes for audio.

**Comment by mattgodbolt** [comment]
Fix is merged; hard to tell if it's fixed - there's a flickery mass still whereas I remember the screen basically hanging when you held break. I wonder if this is the fact we only poll for keys once a frame, so holding down break only causes it to reset once a frame. I suspect a real beeb would be stuck in the reset handler until you let go of break.

**Comment by richtw1** [comment]
I think there are two separate issues.  For me the graphical mess is fixed, but agree that Break shouldn't be autorepeating.  I don't know if reset is edge triggered or just that it will be continually asserted after every instruction as you suggest (but that we have a granularity of a frame).
