### ISSUE TITLE
Make the "boo" of the "boo-beep" startup sound work properly

### ISSUE THREAD

**Issue by jlarcombe** [mattgodbolt/jsbeeb#97]
Been using jsbeeb a lot recently and it's great, but it's disorientating to have only one start-up beep!

I tried the suggested change in the reset function in SoundChip, and it works fine here on a Mac Book Pro with Chrome. Are the start-up glitches on Linux perhaps, where the overall audio system tends to need a lot more buffering? Even so, the buffer size supplied to the AudioContext on initialisation seems generous enough (2048 frames). So I'd be curious to learn more about the nature of the problem.

**Comment by mattgodbolt** [comment]
Got there...nearly ten years later :)
