### ISSUE TITLE
Support "h-sync pulse width CRT hack to allow half character horizontal scrolling"

### ISSUE THREAD

**Issue by murkle** [mattgodbolt/jsbeeb#98]
http://web.archive.org/web/20150630040547/http://www.retrosoftware.co.uk/forum/viewtopic.php?f=19&t=903

In jsbeeb the vertical scrolling looks perfect. The horizontal doesn't look as good (maybe needs testing on a real BBC or maybe just BEm to compare)

**Comment by richtw1** [comment]
Is this not fixed? This should've been sorted with the other video changes I made recently.

**Comment by richtw1** [comment]
For reference, "demo of 1000 scrolls" off the 3d Pool disc looks right to me, including the mud screen change of CRTC R3.

**Comment by richtw1** [comment]
mid *

**Comment by murkle** [comment]
OK, great - thanks for checking :)

**Comment by richtw1** [comment]
Confirmed - this works OK on the latest version of jsbeeb (provided the timings in the demo are correctly configured by pressing 'Y', 'A' and 'V').
