### ISSUE TITLE
jsbeeb hangs when left running in the background for a long time

### ISSUE THREAD

**Issue by richtw1** [mattgodbolt/jsbeeb#99]
Keyboard unresponsive, video not updating (cursor not flashing).  This was on Win 8.1, Google Chrome.  Still seems to be running.

**Comment by mattgodbolt** [comment]
Almost certainly due to the cpuCounter running out of precision above ~4 billion (35 minutes). I thought of this the other day and realised the change I'd made to keep cpuCycles monotonic would have this side effect...

**Comment by richtw1** [comment]
Yeah I wondered if it would be that.  35 minutes sounds pretty much exactly right.

**Comment by mattgodbolt** [comment]
Stupid javascript.
